// Code generated by core. DO NOT EDIT (base, regenerated each run).
package base

import (
	"encoding/csv"
	"fmt"
	"strings"
)

// BaseUnitRow 表 "unit" 的一行（强类型）。
type BaseUnitRow struct {
	Id int // 本表主键（26020001 起；本项目自定）
	Key string // 实体键：卡牌行为卡牌 key（逐字=官方 cards.json:key）；非卡牌实体为官方实体名（官方 cards_stats_*.json:name，逐字）
	NameCn string // 中文名（参考规格 §6/§4.1；官方数据无中文名的实体留空；本项目自定）
	Kind int // 0=部队 1=建筑 2=塔 3=投射物（本项目自定）
	Hp int // 生命值（11 级）← 官方 hitpoints_per_level[tournament_level_index]
	Damage int // 单发伤害（11 级）；官方 damage_per_level[索引]；本体为 0 时取其上投射物（projectile_key）的 damage_per_level
	HitSpeedMs int // 攻击间隔 ms ← 官方 hit_speed
	LoadTimeMs int // 首次攻击前摇 ms ← 官方 load_time
	Speed int // 移动速度（格/分钟）← 官方 speed；投射物行为弹道速度（官方 cards_stats_projectile.json:speed）
	RangeMt int // 攻击射程 milli-tile ← 官方 range
	SightMt int // 视野 milli-tile ← 官方 sight_range
	DeployMs int // 部署延迟 ms ← 官方 deploy_time
	RadiusMt int // 碰撞半径 milli-tile ← 官方 collision_radius；投射物行为弹体半径（官方 cards_stats_projectile.json:radius）
	Mass int // 质量（推挤分离用）← 官方 mass
	AtkAir int // 能否攻击空中 0/1 ← 官方 attacks_air
	AtkGround int // 能否攻击地面 0/1 ← 官方 attacks_ground
	OnlyBuildings int // 只打建筑 0/1 ← 官方 target_only_buildings
	OnlyTowers int // 只打塔 0/1 ← 官方 target_only_towers
	OnlyTroops int // 只打部队 0/1 ← 官方 target_only_troops
	ProjectileKey string // 攻击投射物实体 key（对应本表 kind=3 的行）；取值=官方 custom_first_projectile（有则优先，携带伤害）否则 projectile
	DeathSpawnKey string // 亡语召唤实体 key ← 官方 death_spawn_character
	DeathSpawnN int // 亡语召唤数量 ← 官方 death_spawn_count
	DeathDamage int // 亡语伤害（11 级）← 官方 death_damage
	DeathAoeRadiusMt int // 亡语爆炸半径 milli-tile ← 官方 death_damage_radius
	LifeMs int // 存活时长 ms（建筑/临时实体）← 官方 life_time
	SpawnKey string // 周期性召唤实体 key ← 官方 spawn_character
	SpawnN int // 周期性召唤数量 ← 官方 spawn_number
	SpawnRadiusMt int // 周期性召唤铺设半径 milli-tile ← 官方 spawn_radius
	SpawnIntervalMs int // 周期性召唤**波间隔** ms ← 官方 spawn_pause_time（哥布林小屋 10000 / 野蛮人小屋 14000 / 骷髅墓碑 3500 / 女巫 7000；0 = 只有一波）
	SpawnLimit int // 场上召唤上限（**存活子代数**上限）← 官方 spawn_limit
	SummonKey string // 落点召唤实体 key（群体卡）← 本项目自定：本表内部行 key（与官方 cards_stats_troop.json:summon_character 同名）
	SummonN int // 落点召唤数量 ← 本项目自定（口径同官方 summon_number）
	SummonRadiusMt int // 落点环形铺设半径 milli-tile ← 本项目自定（口径同官方 summon_radius；0 = 由引擎按"相邻不重叠"铺开）
	SummonDeployDelayMs int // 落点召唤的**逐个错开**部署间隔 ms ← 本项目自定（口径同官方 summon_deploy_delay；第 i 只 = 自身 deploy_time + i × 本值）
	AoeRadiusMt int // 普攻溅射半径 milli-tile（0=无溅射）← 角色行为官方 area_damage_radius；**投射物行**为官方 cards_stats_projectile.json:radius（法师 1500 / 屠夫 1000 / 滚石 1800 …）
	SpriteDir string // 素材目录名（本项目自定：参考规格 §6）
	Flying int // 1=飞行单位（官方 cards_stats_characters.json 的 flying_height>0）；0=地面（建筑/塔/投射物恒 0）
	SpawnStaggerMs int // 周期性召唤**波内错开**间隔 ms ← 官方 spawn_interval（小屋 500；0 = 一波同时出）
	JumpHeightMt int // 可跳过的水域宽度 milli-tile ← 官方 jump_height（jump_enabled=true 的 4 张卡：野猪骑士/王子/黑暗王子/野蛮人攻城槌 = 4000；0 = 不能跳河）
	JumpSpeed int // 跳跃期间水平速度（格/分钟）← 官方 jump_speed（同上 4 张卡 = 160；0 = 不跳）
}

// BaseUnitTable 表 "unit" 的只读容器（按主键索引）。
type BaseUnitTable struct {
	rows  []*BaseUnitRow
	index map[int]*BaseUnitRow
}

// NewBaseUnitTable 创建空表。
func NewBaseUnitTable() *BaseUnitTable {
	return &BaseUnitTable{index: make(map[int]*BaseUnitRow)}
}

// Get 按主键取行（不存在返回 nil）。
func (t *BaseUnitTable) Get(id int) *BaseUnitRow {
	return t.index[id]
}

// Len 当前行数。
func (t *BaseUnitTable) Len() int { return len(t.rows) }

// Rows 返回全部行（只读视图）。
func (t *BaseUnitTable) Rows() []*BaseUnitRow { return t.rows }

// Load 从 tsv 文本加载（首行为列名表头，'\t' 分隔）。整体替换旧数据。
// redis 等内存源拿到原始 tsv 文本直接传 content；file 源由 registry 读取后传入。
func (t *BaseUnitTable) Load(content string) error {
	r := csv.NewReader(strings.NewReader(content))
	r.Comma = '\t'
	r.FieldsPerRecord = -1
	r.TrimLeadingSpace = true
	recs, err := r.ReadAll()
	if err != nil {
		return fmt.Errorf("BaseUnitTable: 解析 tsv 失败: %w", err)
	}
	if len(recs) < 1 {
		return fmt.Errorf("BaseUnitTable: tsv 无数据")
	}
	// 整体替换
	t.rows = nil
	t.index = make(map[int]*BaseUnitRow)
	for _, rec := range recs[1:] {
		row := &BaseUnitRow{}
		row.Id = parseInt(cell(rec, 0))
		row.Key = cell(rec, 1)
		row.NameCn = cell(rec, 2)
		row.Kind = parseInt(cell(rec, 3))
		row.Hp = parseInt(cell(rec, 4))
		row.Damage = parseInt(cell(rec, 5))
		row.HitSpeedMs = parseInt(cell(rec, 6))
		row.LoadTimeMs = parseInt(cell(rec, 7))
		row.Speed = parseInt(cell(rec, 8))
		row.RangeMt = parseInt(cell(rec, 9))
		row.SightMt = parseInt(cell(rec, 10))
		row.DeployMs = parseInt(cell(rec, 11))
		row.RadiusMt = parseInt(cell(rec, 12))
		row.Mass = parseInt(cell(rec, 13))
		row.AtkAir = parseInt(cell(rec, 14))
		row.AtkGround = parseInt(cell(rec, 15))
		row.OnlyBuildings = parseInt(cell(rec, 16))
		row.OnlyTowers = parseInt(cell(rec, 17))
		row.OnlyTroops = parseInt(cell(rec, 18))
		row.ProjectileKey = cell(rec, 19)
		row.DeathSpawnKey = cell(rec, 20)
		row.DeathSpawnN = parseInt(cell(rec, 21))
		row.DeathDamage = parseInt(cell(rec, 22))
		row.DeathAoeRadiusMt = parseInt(cell(rec, 23))
		row.LifeMs = parseInt(cell(rec, 24))
		row.SpawnKey = cell(rec, 25)
		row.SpawnN = parseInt(cell(rec, 26))
		row.SpawnRadiusMt = parseInt(cell(rec, 27))
		row.SpawnIntervalMs = parseInt(cell(rec, 28))
		row.SpawnLimit = parseInt(cell(rec, 29))
		row.SummonKey = cell(rec, 30)
		row.SummonN = parseInt(cell(rec, 31))
		row.SummonRadiusMt = parseInt(cell(rec, 32))
		row.SummonDeployDelayMs = parseInt(cell(rec, 33))
		row.AoeRadiusMt = parseInt(cell(rec, 34))
		row.SpriteDir = cell(rec, 35)
		row.Flying = parseInt(cell(rec, 36))
		row.SpawnStaggerMs = parseInt(cell(rec, 37))
		row.JumpHeightMt = parseInt(cell(rec, 38))
		row.JumpSpeed = parseInt(cell(rec, 39))
		t.rows = append(t.rows, row)
		t.index[row.Id] = row
	}
	return nil
}

// Clear 清空全部数据。
func (t *BaseUnitTable) Clear() {
	t.rows = nil
	t.index = make(map[int]*BaseUnitRow)
}
