// Code generated by core. DO NOT EDIT (base, regenerated each run).
package base

import (
	"encoding/csv"
	"fmt"
	"strings"
)

// BaseSpellRow 表 "spell" 的一行（强类型）。
type BaseSpellRow struct {
	Id int // 本表主键（26030001 起）
	Key string // 卡牌 key（与 卡牌_cs.key 一致）
	NameCn string // 中文名
	Elixir int // 圣水消耗
	Rarity int // 0=普通 1=稀有 2=史诗 3=传说
	RadiusMt int // 作用半径 milli-tile
	InstantDamage int // 立即伤害（11 级）；持续伤害型为 0
	CrownDamage int // 对王冠塔的实际伤害 = 伤害 x (1+crown_tower_damage_percent/100)
	DurationMs int // 作用区存活时长 ms（官方 life_duration）
	TickMs int // 持续伤害结算间隔 ms（官方 buff hit_frequency）
	DamagePerTick int // 每跳伤害（11 级；= 每秒伤害 x 1.1^tournament_level_index x tick/1000）
	HealPerSecond int // 每秒治疗量
	SpawnKey string // 法术召唤的实体 key
	SpawnN int // 法术召唤数量
	SpawnRadiusMt int // 法术召唤铺设半径 milli-tile
	Pushback int // 击退力（milli-tile）
	Anywhere int // 能否落敌方半场 0/1
	OnWater int // 能否落河面 0/1
	SpriteDir string // 卡面素材目录名
}

// BaseSpellTable 表 "spell" 的只读容器（按主键索引）。
type BaseSpellTable struct {
	rows  []*BaseSpellRow
	index map[int]*BaseSpellRow
}

// NewBaseSpellTable 创建空表。
func NewBaseSpellTable() *BaseSpellTable {
	return &BaseSpellTable{index: make(map[int]*BaseSpellRow)}
}

// Get 按主键取行（不存在返回 nil）。
func (t *BaseSpellTable) Get(id int) *BaseSpellRow {
	return t.index[id]
}

// Len 当前行数。
func (t *BaseSpellTable) Len() int { return len(t.rows) }

// Rows 返回全部行（只读视图）。
func (t *BaseSpellTable) Rows() []*BaseSpellRow { return t.rows }

// Load 从 tsv 文本加载（首行为列名表头，'\t' 分隔）。整体替换旧数据。
// redis 等内存源拿到原始 tsv 文本直接传 content；file 源由 registry 读取后传入。
func (t *BaseSpellTable) Load(content string) error {
	r := csv.NewReader(strings.NewReader(content))
	r.Comma = '\t'
	r.FieldsPerRecord = -1
	r.TrimLeadingSpace = true
	recs, err := r.ReadAll()
	if err != nil {
		return fmt.Errorf("BaseSpellTable: 解析 tsv 失败: %w", err)
	}
	if len(recs) < 1 {
		return fmt.Errorf("BaseSpellTable: tsv 无数据")
	}
	// 整体替换
	t.rows = nil
	t.index = make(map[int]*BaseSpellRow)
	for _, rec := range recs[1:] {
		row := &BaseSpellRow{}
		row.Id = parseInt(cell(rec, 0))
		row.Key = cell(rec, 1)
		row.NameCn = cell(rec, 2)
		row.Elixir = parseInt(cell(rec, 3))
		row.Rarity = parseInt(cell(rec, 4))
		row.RadiusMt = parseInt(cell(rec, 5))
		row.InstantDamage = parseInt(cell(rec, 6))
		row.CrownDamage = parseInt(cell(rec, 7))
		row.DurationMs = parseInt(cell(rec, 8))
		row.TickMs = parseInt(cell(rec, 9))
		row.DamagePerTick = parseInt(cell(rec, 10))
		row.HealPerSecond = parseInt(cell(rec, 11))
		row.SpawnKey = cell(rec, 12)
		row.SpawnN = parseInt(cell(rec, 13))
		row.SpawnRadiusMt = parseInt(cell(rec, 14))
		row.Pushback = parseInt(cell(rec, 15))
		row.Anywhere = parseInt(cell(rec, 16))
		row.OnWater = parseInt(cell(rec, 17))
		row.SpriteDir = cell(rec, 18)
		t.rows = append(t.rows, row)
		t.index[row.Id] = row
	}
	return nil
}

// Clear 清空全部数据。
func (t *BaseSpellTable) Clear() {
	t.rows = nil
	t.index = make(map[int]*BaseSpellRow)
}
