// Code generated by core. DO NOT EDIT (base, regenerated each run).
package base

import "fmt"

// BaseSpellRow 表 "spell" 的一行（强类型）。
type BaseSpellRow struct {
	Id int // 本表主键（26030001 起）
	Key string // 卡牌 key（与 卡牌_cs.key 一致）
	NameCn string // 中文名
	Elixir int // 圣水消耗
	Rarity int // 0=普通 1=稀有 2=史诗 3=传说
	RadiusMt int // 作用半径 milli-tile
	InstantDamage int // 立即伤害（11 级）；持续伤害型为 0
	CrownDamage int // 对王冠塔的实际伤害 = 伤害 x (1+crown_tower_damage_percent/100)
	DurationMs int // 作用区存活时长 ms（官方 life_duration）
	TickMs int // 持续伤害结算间隔 ms（官方 buff hit_frequency）
	DamagePerTick int // 每跳伤害（11 级；= 每秒伤害 x 1.1^tournament_level_index x tick/1000）
	HealPerSecond int // 每秒治疗量
	SpawnKey string // 法术召唤的实体 key
	SpawnN int // 法术召唤数量
	SpawnRadiusMt int // 法术召唤铺设半径 milli-tile
	Pushback int // 击退力（milli-tile）
	Anywhere int // 能否落敌方半场 0/1
	OnWater int // 能否落河面 0/1
	SpriteDir string // 卡面素材目录名
}

// BaseSpellTable 表 "spell" 的只读容器（按主键索引）。
type BaseSpellTable struct {
	rows  []*BaseSpellRow
	index map[int]*BaseSpellRow
}

// NewBaseSpellTable 创建空表。
func NewBaseSpellTable() *BaseSpellTable {
	return &BaseSpellTable{index: make(map[int]*BaseSpellRow)}
}

// Get 按主键取行（不存在返回 nil）。
func (t *BaseSpellTable) Get(id int) *BaseSpellRow {
	return t.index[id]
}

// Len 当前行数。
func (t *BaseSpellTable) Len() int { return len(t.rows) }

// Rows 返回全部行（只读视图）。
func (t *BaseSpellTable) Rows() []*BaseSpellRow { return t.rows }

// Load 从 tsv 文本加载（首行为列名表头，'\t' 分隔）。整体替换旧数据。
// redis 等内存源拿到原始 tsv 文本直接传 content；file 源由 registry 读取后传入。
//
// ★ 取值一律按**列名**（不是按下标）：源表插列 / 换列序不会让字段整体错位。
// ★ 三类 fail-fast：① 字段数与表头不一致；② 表头缺本实现要读的列；③ 整型 / 浮点列出现非法值。
// 口径出处：clover-project-cr/server/game/table/tsv.go（首次上浮到生成模板），详见 base_table.go 顶部。
func (t *BaseSpellTable) Load(content string) error {
	header, recs, err := splitTSV(content)
	if err != nil {
		return fmt.Errorf("BaseSpellTable: %w", err)
	}
	c, err := newCols("spell", header)
	if err != nil {
		return err
	}
	if err := c.require(
		"id", "key", "name_cn", "elixir", "rarity", "radius_mt", "instant_damage", "crown_damage",
		"duration_ms", "tick_ms", "damage_per_tick", "heal_per_second", "spawn_key", "spawn_n", "spawn_radius_mt", "pushback",
		"anywhere", "on_water", "sprite_dir"); err != nil {
		return err
	}
	// 整体替换
	t.rows = nil
	t.index = make(map[int]*BaseSpellRow)
	for i, rec := range recs {
		c.line = i + 2 // +1 = 数据行，+1 = 表头占了一行
		if err := checkRowWidth("spell", header, rec, c.line); err != nil {
			return err
		}
		row := &BaseSpellRow{}
		row.Id = c.int(rec, "id")
		row.Key = c.str(rec, "key")
		row.NameCn = c.str(rec, "name_cn")
		row.Elixir = c.int(rec, "elixir")
		row.Rarity = c.int(rec, "rarity")
		row.RadiusMt = c.int(rec, "radius_mt")
		row.InstantDamage = c.int(rec, "instant_damage")
		row.CrownDamage = c.int(rec, "crown_damage")
		row.DurationMs = c.int(rec, "duration_ms")
		row.TickMs = c.int(rec, "tick_ms")
		row.DamagePerTick = c.int(rec, "damage_per_tick")
		row.HealPerSecond = c.int(rec, "heal_per_second")
		row.SpawnKey = c.str(rec, "spawn_key")
		row.SpawnN = c.int(rec, "spawn_n")
		row.SpawnRadiusMt = c.int(rec, "spawn_radius_mt")
		row.Pushback = c.int(rec, "pushback")
		row.Anywhere = c.int(rec, "anywhere")
		row.OnWater = c.int(rec, "on_water")
		row.SpriteDir = c.str(rec, "sprite_dir")
		if c.err != nil {
			return c.err
		}
		t.rows = append(t.rows, row)
		t.index[row.Id] = row
	}
	return nil
}

// Clear 清空全部数据。
func (t *BaseSpellTable) Clear() {
	t.rows = nil
	t.index = make(map[int]*BaseSpellRow)
}
