// Code generated by core. DO NOT EDIT (base, regenerated each run).
package base

import "fmt"

// BaseUnitRow 表 "unit" 的一行（强类型）。
type BaseUnitRow struct {
	Id int // 本表主键（26020001 起；本项目自定）
	Key string // 实体键：卡牌行为卡牌 key（逐字=官方 cards.json:key）；非卡牌实体为官方实体名（官方 cards_stats_*.json:name，逐字）
	NameCn string // 中文名（参考规格 §6/§4.1；官方数据无中文名的实体留空；本项目自定）
	Kind int // 0=部队 1=建筑 2=塔 3=投射物（本项目自定）
	Hp int // 生命值（11 级）← 官方 hitpoints_per_level[tournament_level_index]
	Damage int // 单发伤害（11 级）；官方 damage_per_level[索引]；本体为 0 时取其上投射物（projectile_key）的 damage_per_level
	HitSpeedMs int // 攻击间隔 ms ← 官方 hit_speed
	LoadTimeMs int // 首次攻击前摇 ms ← 官方 load_time
	Speed int // 移动速度（格/分钟）← 官方 speed；投射物行为弹道速度（官方 cards_stats_projectile.json:speed）
	RangeMt int // 攻击射程 milli-tile ← 官方 range
	SightMt int // 视野 milli-tile ← 官方 sight_range
	DeployMs int // 部署延迟 ms ← 官方 deploy_time
	RadiusMt int // 碰撞半径 milli-tile ← 官方 collision_radius；投射物行为弹体半径（官方 cards_stats_projectile.json:radius）
	Mass int // 质量（推挤分离用）← 官方 mass
	AtkAir int // 能否攻击空中 0/1 ← 官方 attacks_air
	AtkGround int // 能否攻击地面 0/1 ← 官方 attacks_ground
	OnlyBuildings int // 只打建筑 0/1 ← 官方 target_only_buildings
	OnlyTowers int // 只打塔 0/1 ← 官方 target_only_towers
	OnlyTroops int // 只打部队 0/1 ← 官方 target_only_troops
	ProjectileKey string // 攻击投射物实体 key（对应本表 kind=3 的行）；取值=官方 custom_first_projectile（有则优先，携带伤害）否则 projectile
	DeathSpawnKey string // 亡语召唤实体 key ← 官方 death_spawn_character
	DeathSpawnN int // 亡语召唤数量 ← 官方 death_spawn_count
	DeathDamage int // 亡语伤害（11 级）← 官方 death_damage
	DeathAoeRadiusMt int // 亡语爆炸半径 milli-tile ← 官方 death_damage_radius
	LifeMs int // 存活时长 ms（建筑/临时实体）← 官方 life_time
	SpawnKey string // 周期性召唤实体 key ← 官方 spawn_character
	SpawnN int // 周期性召唤数量 ← 官方 spawn_number
	SpawnRadiusMt int // 周期性召唤铺设半径 milli-tile ← 官方 spawn_radius
	SpawnIntervalMs int // 周期性召唤间隔 ms ← 官方 spawn_interval（非零时取之，否则 spawn_pause_time）
	SpawnLimit int // 场上召唤上限 ← 官方 spawn_limit
	SummonKey string // 落点召唤实体 key（群体卡）← 本项目自定：本表内部行 key（与官方 cards_stats_troop.json:summon_character 同名）
	SummonN int // 落点召唤数量 ← 本项目自定（口径同官方 summon_number）
	SummonRadiusMt int // 落点环形铺设半径 milli-tile ← 本项目自定（口径同官方 summon_radius）
	SummonDeployDelayMs int // 落点召唤的部署延迟 ms ← 本项目自定（口径同官方 summon_deploy_delay）
	AoeRadiusMt int // 普攻溅射半径 milli-tile（0=无溅射）← 官方 area_damage_radius
	SpriteDir string // 素材目录名（本项目自定：参考规格 §6）
	Flying int // 1=飞行单位（官方 cards_stats_characters.json 的 flying_height>0）；0=地面（建筑/塔/投射物恒 0）
	SpawnStaggerMs int
	JumpHeightMt int
	JumpSpeed int
}

// BaseUnitTable 表 "unit" 的只读容器（按主键索引）。
type BaseUnitTable struct {
	rows  []*BaseUnitRow
	index map[int]*BaseUnitRow
}

// NewBaseUnitTable 创建空表。
func NewBaseUnitTable() *BaseUnitTable {
	return &BaseUnitTable{index: make(map[int]*BaseUnitRow)}
}

// Get 按主键取行（不存在返回 nil）。
func (t *BaseUnitTable) Get(id int) *BaseUnitRow {
	return t.index[id]
}

// Len 当前行数。
func (t *BaseUnitTable) Len() int { return len(t.rows) }

// Rows 返回全部行（只读视图）。
func (t *BaseUnitTable) Rows() []*BaseUnitRow { return t.rows }

// Load 从 tsv 文本加载（首行为列名表头，'\t' 分隔）。整体替换旧数据。
// redis 等内存源拿到原始 tsv 文本直接传 content；file 源由 registry 读取后传入。
//
// ★ 取值一律按**列名**（不是按下标）：源表插列 / 换列序不会让字段整体错位。
// ★ 三类 fail-fast：① 字段数与表头不一致；② 表头缺本实现要读的列；③ 整型 / 浮点列出现非法值。
// 口径出处：clover-project-cr/server/game/table/tsv.go（首次上浮到生成模板），详见 base_table.go 顶部。
func (t *BaseUnitTable) Load(content string) error {
	header, recs, err := splitTSV(content)
	if err != nil {
		return fmt.Errorf("BaseUnitTable: %w", err)
	}
	c, err := newCols("unit", header)
	if err != nil {
		return err
	}
	if err := c.require(
		"id", "key", "name_cn", "kind", "hp", "damage", "hit_speed_ms", "load_time_ms",
		"speed", "range_mt", "sight_mt", "deploy_ms", "radius_mt", "mass", "atk_air", "atk_ground",
		"only_buildings", "only_towers", "only_troops", "projectile_key", "death_spawn_key", "death_spawn_n", "death_damage", "death_aoe_radius_mt",
		"life_ms", "spawn_key", "spawn_n", "spawn_radius_mt", "spawn_interval_ms", "spawn_limit", "summon_key", "summon_n",
		"summon_radius_mt", "summon_deploy_delay_ms", "aoe_radius_mt", "sprite_dir", "flying", "spawn_stagger_ms", "jump_height_mt", "jump_speed"); err != nil {
		return err
	}
	// 整体替换
	t.rows = nil
	t.index = make(map[int]*BaseUnitRow)
	for i, rec := range recs {
		c.line = i + 2 // +1 = 数据行，+1 = 表头占了一行
		if err := checkRowWidth("unit", header, rec, c.line); err != nil {
			return err
		}
		row := &BaseUnitRow{}
		row.Id = c.int(rec, "id")
		row.Key = c.str(rec, "key")
		row.NameCn = c.str(rec, "name_cn")
		row.Kind = c.int(rec, "kind")
		row.Hp = c.int(rec, "hp")
		row.Damage = c.int(rec, "damage")
		row.HitSpeedMs = c.int(rec, "hit_speed_ms")
		row.LoadTimeMs = c.int(rec, "load_time_ms")
		row.Speed = c.int(rec, "speed")
		row.RangeMt = c.int(rec, "range_mt")
		row.SightMt = c.int(rec, "sight_mt")
		row.DeployMs = c.int(rec, "deploy_ms")
		row.RadiusMt = c.int(rec, "radius_mt")
		row.Mass = c.int(rec, "mass")
		row.AtkAir = c.int(rec, "atk_air")
		row.AtkGround = c.int(rec, "atk_ground")
		row.OnlyBuildings = c.int(rec, "only_buildings")
		row.OnlyTowers = c.int(rec, "only_towers")
		row.OnlyTroops = c.int(rec, "only_troops")
		row.ProjectileKey = c.str(rec, "projectile_key")
		row.DeathSpawnKey = c.str(rec, "death_spawn_key")
		row.DeathSpawnN = c.int(rec, "death_spawn_n")
		row.DeathDamage = c.int(rec, "death_damage")
		row.DeathAoeRadiusMt = c.int(rec, "death_aoe_radius_mt")
		row.LifeMs = c.int(rec, "life_ms")
		row.SpawnKey = c.str(rec, "spawn_key")
		row.SpawnN = c.int(rec, "spawn_n")
		row.SpawnRadiusMt = c.int(rec, "spawn_radius_mt")
		row.SpawnIntervalMs = c.int(rec, "spawn_interval_ms")
		row.SpawnLimit = c.int(rec, "spawn_limit")
		row.SummonKey = c.str(rec, "summon_key")
		row.SummonN = c.int(rec, "summon_n")
		row.SummonRadiusMt = c.int(rec, "summon_radius_mt")
		row.SummonDeployDelayMs = c.int(rec, "summon_deploy_delay_ms")
		row.AoeRadiusMt = c.int(rec, "aoe_radius_mt")
		row.SpriteDir = c.str(rec, "sprite_dir")
		row.Flying = c.int(rec, "flying")
		row.SpawnStaggerMs = c.int(rec, "spawn_stagger_ms")
		row.JumpHeightMt = c.int(rec, "jump_height_mt")
		row.JumpSpeed = c.int(rec, "jump_speed")
		if c.err != nil {
			return c.err
		}
		t.rows = append(t.rows, row)
		t.index[row.Id] = row
	}
	return nil
}

// Clear 清空全部数据。
func (t *BaseUnitTable) Clear() {
	t.rows = nil
	t.index = make(map[int]*BaseUnitRow)
}
