// Code generated by core. DO NOT EDIT (base runtime, regenerated each run).
package base

import (
	"fmt"
	"strconv"
	"strings"
)

// Vector3 三维向量（策划用 ';' 或 ',' 分隔的三个浮点数）。
type Vector3 struct {
	X float32
	Y float32
	Z float32
}

// cell 安全取第 i 个单元格（越界返回空串）。
func cell(rec []string, i int) string {
	if i < 0 || i >= len(rec) {
		return ""
	}
	return rec[i]
}

// ─────────────────────────────────────────────────────────────────────────────
// TSV 解析：按列名取值 + 三类 fail-fast
//
// ★ 为什么按**列名**取值，而不是按下标（cell(rec, i)）：
//   下标把「生成的代码」和「源表的列顺序」硬绑在一起 —— 策划在源表中间插一列，
//   base 层一旦没跟着重新生成，其后所有字段就会整体错位，而且**不报任何错**：
//   跑起来数值全错，看起来却一切正常。按列名取值（表头先建 name→index 索引）与列序无关。
//
// ★ 为什么不用 encoding/csv 而用 strings.Split(line, "\t")：
//   csv 把字段当「带引号规则的文本」解析（字段以 " 开头会触发转义 / 跨行合并），
//   而打表工具写出的 tsv 是「纯 '\t' 拼接、不加引号、不做转义」，客户端 C# 侧也是
//   line.Split('\t')。用 Split 才能保证两端**逐列一致**。
//   行分隔只看 '\n'（并剥掉行尾 '\r'，兼容 CRLF）；空行（含只有空白 / tab 的行）跳过。
//   ⚠️ csv 的另一个坑（本模板一度踩过）：Comma='\t' 且 TrimLeadingSpace=true 时，
//   unicode.IsSpace('\t') 为真 ⇒ 每个空单元格会把它前面那个 tab 一起吃掉 ⇒
//   该行其后字段集体左移且不报错。改用 Split 后此坑从根上消失。
//
// ★ 三类 fail-fast（宁可起服失败，也不让错数据流进业务）：
//   ① 某行字段数与表头不一致（列错位）；② 表头缺本实现要读的列；③ 整型 / 浮点列出现非法值。
//   打表期 def.ValidateCell 已校验过单元格，这里是**运行期**兜底：tsv 可能被手工改过，
//   或被 redis 等内存源灌入。
//
// 口径出处：项目 clover-project-cr，文件 server/game/table/tsv.go（该工程人维护的手写解析器，
// 它正是因为旧 base 层的上述缺陷才绕开 base 自己写了一套）。本次把这套口径上浮到生成
// 模板，使所有项目生成的 base 层默认获得它。
// ─────────────────────────────────────────────────────────────────────────────

// splitTSV 把 tsv 文本切成「表头 + 数据行」。
func splitTSV(content string) ([]string, [][]string, error) {
	lines := strings.Split(content, "\n")
	var header []string
	rows := make([][]string, 0, len(lines))
	for _, raw := range lines {
		line := strings.TrimRight(raw, "\r")
		if strings.TrimSpace(line) == "" {
			continue
		}
		if header == nil {
			header = strings.Split(line, "\t")
			continue
		}
		rows = append(rows, strings.Split(line, "\t"))
	}
	if header == nil {
		return nil, nil, fmt.Errorf("tsv 无内容")
	}
	return header, rows, nil
}

// cols 表头索引 + 取值器：取值一律按**列名**。
// 取值错误（整型 / 浮点列非法值）先记在 err 上，由调用方在构造完一行后检查 ——
// 这样每个字段一行代码，错误信息里仍能带上表名 / 行号 / 列名。
type cols struct {
	table string
	raw   []string       // 表头列名（去首尾空白，按原列顺序）
	idx   map[string]int // 列名 → 列下标
	line  int            // 当前数据行号（1 = 表头，故第 1 行数据是 2）
	err   error          // 首个取值错误（nil = 至今没有错误）
}

// newCols 建表头索引。列名去首尾空白；重复列名直接报错（重复列必然让取值语义含糊）。
func newCols(tableName string, header []string) (*cols, error) {
	c := &cols{table: tableName, raw: make([]string, len(header)), idx: make(map[string]int, len(header))}
	for i, h := range header {
		h = strings.TrimSpace(h)
		c.raw[i] = h
		if h == "" {
			continue // 打表工具不写空列名；真出现就跳过（按该名取值恒为空）
		}
		if _, dup := c.idx[h]; dup {
			return nil, fmt.Errorf("%s: 表头有重复列名 %q", tableName, h)
		}
		c.idx[h] = i
	}
	return c, nil
}

// require 校验表头包含本实现会读的全部列。
// 漏一列会让对应字段恒为 0 / 空（静默错），所以这里 fail-fast 并把实际表头打出来。
func (c *cols) require(cols ...string) error {
	var miss []string
	for _, col := range cols {
		if _, ok := c.idx[col]; !ok {
			miss = append(miss, col)
		}
	}
	if len(miss) > 0 {
		return fmt.Errorf("%s: 表头缺少列 %s；实际表头 = [%s]",
			c.table, strings.Join(miss, ", "), strings.Join(c.header(), " "))
	}
	return nil
}

// header 还原表头（报错信息用）：形如 [#0=id #1=key …]，按列下标顺序。
func (c *cols) header() []string {
	out := make([]string, 0, len(c.idx))
	for i, h := range c.raw {
		if h == "" {
			continue
		}
		out = append(out, fmt.Sprintf("#%d=%s", i, h))
	}
	return out
}

// str 取字符串列（列不存在 / 越界 / 单元格为空都返回空串）。
func (c *cols) str(rec []string, col string) string {
	i, ok := c.idx[col]
	if !ok || i < 0 || i >= len(rec) {
		return ""
	}
	return strings.TrimSpace(rec[i])
}

// fail 记下首个取值错误（只报第一个：后面的多半是同一处故障的连带）。
func (c *cols) fail(col, val, want string) {
	if c.err == nil {
		c.err = fmt.Errorf("%s: 第 %d 行列 %s 的值 %q 不是%s", c.table, c.line, col, val, want)
	}
}

// int 取整型列：空单元格 → 0（合法留空）；非整数 → 记错误、返回 0（不再静默按 0）。
func (c *cols) int(rec []string, col string) int {
	s := c.str(rec, col)
	if s == "" {
		return 0
	}
	v, err := strconv.Atoi(s)
	if err != nil {
		c.fail(col, s, "整数")
		return 0
	}
	return v
}

// int32 取 int32 列（口径同 int，含范围校验）。
func (c *cols) int32(rec []string, col string) int32 {
	s := c.str(rec, col)
	if s == "" {
		return 0
	}
	v, err := strconv.ParseInt(s, 10, 32)
	if err != nil {
		c.fail(col, s, "整数(int32)")
		return 0
	}
	return int32(v)
}

// int64 取 int64 列（口径同 int）。
func (c *cols) int64(rec []string, col string) int64 {
	s := c.str(rec, col)
	if s == "" {
		return 0
	}
	v, err := strconv.ParseInt(s, 10, 64)
	if err != nil {
		c.fail(col, s, "整数(int64)")
		return 0
	}
	return v
}

// float64 取 float64 列：空单元格 → 0；非浮点 → 记错误、返回 0。
func (c *cols) float64(rec []string, col string) float64 {
	s := c.str(rec, col)
	if s == "" {
		return 0
	}
	v, err := strconv.ParseFloat(s, 64)
	if err != nil {
		c.fail(col, s, "浮点数")
		return 0
	}
	return v
}

// float32 取 float32 列（口径同 float64，末尾收窄）。
func (c *cols) float32(rec []string, col string) float32 {
	return float32(c.float64(rec, col))
}

// checkRowWidth 行宽必须与表头一致：少一列 / 多一列都意味着这行**错位**了，
// 而错位的行是「看起来正常、数值全错」的那种故障。
func checkRowWidth(tableName string, header, rec []string, line int) error {
	if len(rec) != len(header) {
		return fmt.Errorf("%s: 第 %d 行有 %d 列，表头 %d 列（列数不一致 ⇒ 数据错位，拒绝加载）",
			tableName, line, len(rec), len(header))
	}
	return nil
}

func parseInt(s string) int {
	s = strings.TrimSpace(s)
	if s == "" {
		return 0
	}
	v, err := strconv.Atoi(s)
	if err != nil {
		return 0
	}
	return v
}

func parseInt32(s string) int32 {
	s = strings.TrimSpace(s)
	if s == "" {
		return 0
	}
	v, err := strconv.ParseInt(s, 10, 32)
	if err != nil {
		return 0
	}
	return int32(v)
}

func parseInt64(s string) int64 {
	s = strings.TrimSpace(s)
	if s == "" {
		return 0
	}
	v, err := strconv.ParseInt(s, 10, 64)
	if err != nil {
		return 0
	}
	return v
}

func parseFloat32(s string) float32 {
	return float32(parseFloat64(s))
}

func parseFloat64(s string) float64 {
	s = strings.TrimSpace(s)
	if s == "" {
		return 0
	}
	v, err := strconv.ParseFloat(s, 64)
	if err != nil {
		return 0
	}
	return v
}

// parseMapIntInt 解析 "k;v|k;v" 或 "k:v|k:v"（';' 与 ':' 均可作 kv 分隔）。
func parseMapIntInt(s string) map[int]int {
	out := map[int]int{}
	s = strings.TrimSpace(s)
	if s == "" {
		return out
	}
	for _, pair := range strings.Split(s, "|") {
		pair = strings.TrimSpace(pair)
		if pair == "" {
			continue
		}
		kv := strings.SplitN(pair, ";", 2)
		if len(kv) != 2 {
			kv = strings.SplitN(pair, ":", 2)
		}
		if len(kv) != 2 {
			continue
		}
		k := parseInt(kv[0])
		v := parseInt(kv[1])
		out[k] = v
	}
	return out
}

// parseMapIntString 解析 "k;v|k;v"（value 为原样字符串）。
func parseMapIntString(s string) map[int]string {
	out := map[int]string{}
	s = strings.TrimSpace(s)
	if s == "" {
		return out
	}
	for _, pair := range strings.Split(s, "|") {
		pair = strings.TrimSpace(pair)
		if pair == "" {
			continue
		}
		kv := strings.SplitN(pair, ";", 2)
		if len(kv) != 2 {
			kv = strings.SplitN(pair, ":", 2)
		}
		if len(kv) != 2 {
			continue
		}
		out[parseInt(kv[0])] = strings.TrimSpace(kv[1])
	}
	return out
}

// parseSliceInt 解析 "a;b;c"（';' 分隔）。
func parseSliceInt(s string) []int {
	out := []int{}
	s = strings.TrimSpace(s)
	if s == "" {
		return out
	}
	for _, e := range strings.Split(s, ";") {
		e = strings.TrimSpace(e)
		if e == "" {
			continue
		}
		out = append(out, parseInt(e))
	}
	return out
}

// parseSliceFloat 解析 "a;b;c"（';' 分隔的浮点数，如冷却 22;19.5;17）。
func parseSliceFloat(s string) []float32 {
	out := []float32{}
	s = strings.TrimSpace(s)
	if s == "" {
		return out
	}
	for _, e := range strings.Split(s, ";") {
		e = strings.TrimSpace(e)
		if e == "" {
			continue
		}
		out = append(out, parseFloat32(e))
	}
	return out
}

// parseSliceString 解析 "a;b;c"（';' 分隔，保留原样）。
func parseSliceString(s string) []string {
	out := []string{}
	s = strings.TrimSpace(s)
	if s == "" {
		return out
	}
	for _, e := range strings.Split(s, ";") {
		out = append(out, strings.TrimSpace(e))
	}
	return out
}

// parseVector3 解析 "x;y;z" 或 "x,y,z"，取前三个浮点。
func parseVector3(s string) Vector3 {
	var v Vector3
	s = strings.TrimSpace(s)
	if s == "" {
		return v
	}
	sep := ";"
	if !strings.Contains(s, ";") && strings.Contains(s, ",") {
		sep = ","
	}
	parts := strings.Split(s, sep)
	n := 0
	for _, p := range parts {
		f := parseFloat64(p)
		switch n {
		case 0:
			v.X = float32(f)
		case 1:
			v.Y = float32(f)
		case 2:
			v.Z = float32(f)
		default:
			return v
		}
		n++
	}
	return v
}
