// Code generated by core. DO NOT EDIT (base, regenerated each run).
package base

import "fmt"

// BaseCardRow 表 "card" 的一行（强类型）。
type BaseCardRow struct {
	Id int // 本表主键（26010001 起）
	Key string // 官方 cards.json 的 key（逐字）
	NameCn string // 中文名（cards_i18n）
	NameEn string // 英文名（cards_i18n）
	Type int // 0=部队 1=法术 2=建筑
	Rarity int // 0=普通 1=稀有 2=史诗 3=传说
	Elixir int // 圣水消耗
	Arena int // 官方 arena（解锁竞技场）
	Icon string // 客户端卡面图名（约定 card_<key>，由客户端片确定）
	SpriteDir string // 素材目录名（参考规格 §6；多目录以 ; 连接）
	DeployFx string // 部署特效名（官方数据无此字段 ⇒ 留空，待客户端片确定）
}

// BaseCardTable 表 "card" 的只读容器（按主键索引）。
type BaseCardTable struct {
	rows  []*BaseCardRow
	index map[int]*BaseCardRow
}

// NewBaseCardTable 创建空表。
func NewBaseCardTable() *BaseCardTable {
	return &BaseCardTable{index: make(map[int]*BaseCardRow)}
}

// Get 按主键取行（不存在返回 nil）。
func (t *BaseCardTable) Get(id int) *BaseCardRow {
	return t.index[id]
}

// Len 当前行数。
func (t *BaseCardTable) Len() int { return len(t.rows) }

// Rows 返回全部行（只读视图）。
func (t *BaseCardTable) Rows() []*BaseCardRow { return t.rows }

// Load 从 tsv 文本加载（首行为列名表头，'\t' 分隔）。整体替换旧数据。
// redis 等内存源拿到原始 tsv 文本直接传 content；file 源由 registry 读取后传入。
//
// ★ 取值一律按**列名**（不是按下标）：源表插列 / 换列序不会让字段整体错位。
// ★ 三类 fail-fast：① 字段数与表头不一致；② 表头缺本实现要读的列；③ 整型 / 浮点列出现非法值。
// 口径出处：clover-project-cr/server/game/table/tsv.go（首次上浮到生成模板），详见 base_table.go 顶部。
func (t *BaseCardTable) Load(content string) error {
	header, recs, err := splitTSV(content)
	if err != nil {
		return fmt.Errorf("BaseCardTable: %w", err)
	}
	c, err := newCols("card", header)
	if err != nil {
		return err
	}
	if err := c.require(
		"id", "key", "name_cn", "name_en", "type", "rarity", "elixir", "arena",
		"icon", "sprite_dir", "deploy_fx"); err != nil {
		return err
	}
	// 整体替换
	t.rows = nil
	t.index = make(map[int]*BaseCardRow)
	for i, rec := range recs {
		c.line = i + 2 // +1 = 数据行，+1 = 表头占了一行
		if err := checkRowWidth("card", header, rec, c.line); err != nil {
			return err
		}
		row := &BaseCardRow{}
		row.Id = c.int(rec, "id")
		row.Key = c.str(rec, "key")
		row.NameCn = c.str(rec, "name_cn")
		row.NameEn = c.str(rec, "name_en")
		row.Type = c.int(rec, "type")
		row.Rarity = c.int(rec, "rarity")
		row.Elixir = c.int(rec, "elixir")
		row.Arena = c.int(rec, "arena")
		row.Icon = c.str(rec, "icon")
		row.SpriteDir = c.str(rec, "sprite_dir")
		row.DeployFx = c.str(rec, "deploy_fx")
		if c.err != nil {
			return c.err
		}
		t.rows = append(t.rows, row)
		t.index[row.Id] = row
	}
	return nil
}

// Clear 清空全部数据。
func (t *BaseCardTable) Clear() {
	t.rows = nil
	t.index = make(map[int]*BaseCardRow)
}
