// Code generated by core. DO NOT EDIT (base, regenerated each run).
package base

import (
	"encoding/csv"
	"fmt"
	"strings"
)

// BaseCardRow 表 "card" 的一行（强类型）。
type BaseCardRow struct {
	Id int // 本表主键（26010001 起）
	Key string // 官方 cards.json 的 key（逐字）
	NameCn string // 中文名（cards_i18n）
	NameEn string // 英文名（cards_i18n）
	Type int // 0=部队 1=法术 2=建筑
	Rarity int // 0=普通 1=稀有 2=史诗 3=传说
	Elixir int // 圣水消耗
	Arena int // 官方 arena（解锁竞技场）
	Icon string // 客户端卡面图名（约定 card_<key>，由客户端片确定）
	SpriteDir string // 素材目录名（参考规格 §6；多目录以 ; 连接）
	DeployFx string // 部署特效名（官方数据无此字段 ⇒ 留空，待客户端片确定）
}

// BaseCardTable 表 "card" 的只读容器（按主键索引）。
type BaseCardTable struct {
	rows  []*BaseCardRow
	index map[int]*BaseCardRow
}

// NewBaseCardTable 创建空表。
func NewBaseCardTable() *BaseCardTable {
	return &BaseCardTable{index: make(map[int]*BaseCardRow)}
}

// Get 按主键取行（不存在返回 nil）。
func (t *BaseCardTable) Get(id int) *BaseCardRow {
	return t.index[id]
}

// Len 当前行数。
func (t *BaseCardTable) Len() int { return len(t.rows) }

// Rows 返回全部行（只读视图）。
func (t *BaseCardTable) Rows() []*BaseCardRow { return t.rows }

// Load 从 tsv 文本加载（首行为列名表头，'\t' 分隔）。整体替换旧数据。
// redis 等内存源拿到原始 tsv 文本直接传 content；file 源由 registry 读取后传入。
func (t *BaseCardTable) Load(content string) error {
	r := csv.NewReader(strings.NewReader(content))
	r.Comma = '\t'
	r.FieldsPerRecord = -1
	r.TrimLeadingSpace = true
	recs, err := r.ReadAll()
	if err != nil {
		return fmt.Errorf("BaseCardTable: 解析 tsv 失败: %w", err)
	}
	if len(recs) < 1 {
		return fmt.Errorf("BaseCardTable: tsv 无数据")
	}
	// 整体替换
	t.rows = nil
	t.index = make(map[int]*BaseCardRow)
	for _, rec := range recs[1:] {
		row := &BaseCardRow{}
		row.Id = parseInt(cell(rec, 0))
		row.Key = cell(rec, 1)
		row.NameCn = cell(rec, 2)
		row.NameEn = cell(rec, 3)
		row.Type = parseInt(cell(rec, 4))
		row.Rarity = parseInt(cell(rec, 5))
		row.Elixir = parseInt(cell(rec, 6))
		row.Arena = parseInt(cell(rec, 7))
		row.Icon = cell(rec, 8)
		row.SpriteDir = cell(rec, 9)
		row.DeployFx = cell(rec, 10)
		t.rows = append(t.rows, row)
		t.index[row.Id] = row
	}
	return nil
}

// Clear 清空全部数据。
func (t *BaseCardTable) Clear() {
	t.rows = nil
	t.index = make(map[int]*BaseCardRow)
}
