# -*- coding: utf-8 -*-
"""生成 `View/UnitAnimDurations.cs`：**每目录每档的原版时长**（毫秒）。

出处：`策划/单位动画分组表.md` 的「export 名 → clip id → shapeID 全表」小节 —— 每条 export 的
`timeline 帧数` ÷ `FPS` = 该 clip 在**原版**里的播放时长。
为什么需要它：`UnitAnimTable` 的 `Runs` 只存**唯一像素帧**（timeline 里重复帧被折叠掉），
例如 `axe_man_run1_5` = timeline 38 步 / 8 张像素帧 / 60 fps ⇒ 原版周期 0.633 s；
若按 `.sc` 的 60 fps 直接播 8 张像素帧就只有 0.133 s —— 快 4.75 倍（现象 = 走起来在发抖）。
⇒ 规格：该档的像素帧序列要在 `timeline ÷ FPS` 这段时间里播完。
每目录取 **`Source` 里记的默认视角**（`UnitAnimTable` 每档只取一条 clip，通常是 `_5`）的那条 export。

用法（项目根）: python tools/probes/gen-unit-anim-durations.py
输出: client/Assets/Scripts/View/UnitAnimDurations.cs
"""
import os
import re
import sys

ROOT = os.path.abspath(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", ".."))
GROUP = os.path.join(ROOT, "策划", "单位动画分组表.md")
TABLE = os.path.join(ROOT, "client", "Assets", "Scripts", "View", "UnitAnimTable.cs")
OUT = os.path.join(ROOT, "client", "Assets", "Scripts", "View", "UnitAnimDurations.cs")
TIERS = ["idle", "run", "attack", "die"]


def parse_group():
    """export 名 → (clip, fps, timeline, pixels)。"""
    out = {}
    for line in open(GROUP, "r", encoding="utf-8"):
        if not line.startswith("|"):
            continue
        cells = [c.strip() for c in line.strip().strip("|").split("|")]
        if len(cells) < 6:
            continue
        if not re.fullmatch(r"\d+", cells[0]):
            continue
        m = re.fullmatch(r"`([^`]+)`", cells[1])
        if not m:
            continue
        name = m.group(1)
        try:
            fps = int(re.split(r"[,\s]", cells[3])[0])
            tl = int(cells[4])
            px = int(cells[5])
        except (ValueError, IndexError):
            continue
        out[name] = (cells[2], fps, tl, px)
    return out


def parse_table():
    src = open(TABLE, "r", encoding="utf-8").read()
    dirs = []
    for m in re.finditer(r'\["([^"]+)"\] = new Entry \{', src):
        nxt = src.find('["', m.end())
        body = src[m.start(): nxt if nxt > 0 else len(src)]
        exports = re.findall(r'Source = "([^"]*)"', body)
        dirs.append((m.group(1), exports[:4]))
    return dirs


def main():
    g = parse_group()
    dirs = parse_table()
    rows = []
    missing = []
    for d, exports in dirs:
        ms = [0, 0, 0, 0]
        for t, ex in enumerate(exports):
            if not ex:
                continue
            name = ex.split("｜")[0].strip()
            if name not in g:
                missing.append("%s/%s (%s)" % (d, TIERS[t], name))
                continue
            _clip, fps, tl, px = g[name]
            if fps <= 0 or tl <= 0:
                continue
            ms[t] = int(round(tl * 1000.0 / fps))
        rows.append((d, ms, exports))

    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write("// <auto-generated> 由 tools/probes/gen-unit-anim-durations.py 生成 —— 请勿手改；\n")
        f.write("// 改数据请改 `策划/单位动画分组表.md`（生成物）后重跑该脚本。\n")
        f.write("// 数据 = 该目录每档 `Source` 记的那条 export 的 `timeline 帧数 ÷ FPS`（原版播放时长，毫秒）。\n")
        f.write("// 口径：`UnitAnimTable` 的 `Runs` 只存**唯一像素帧**（timeline 里的重复帧已折叠），\n")
        f.write("// 例 `axe_man_run1_5` = timeline 38 步 / 8 张像素帧 / 60 fps ⇒ 原版 0.633 s；\n")
        f.write("// 按 60 fps 直播那 8 张只有 0.133 s（快 4.75 倍）。⇒ 像素帧要在这段时间里播完（见 `UnitView.FpsFor`）。\n")
        f.write("using System.Collections.Generic;\n\nnamespace CR.View\n{\n")
        f.write("    /// <summary>每目录每档的**原版时长**（毫秒；下标 = `UnitAnimTable.Idle/Walk/Attack/Die`）。</summary>\n")
        f.write("    public static class UnitAnimDurations\n    {\n")
        f.write("        /// <summary>档位数（与 <see cref=\"UnitAnimTable\"/> 同）。</summary>\n")
        f.write("        public const int TierCount = 4;\n\n")
        f.write("        private static readonly Dictionary<string, int[]> Table = new Dictionary<string, int[]>\n        {\n")
        for d, ms, exports in rows:
            f.write('            { "%s", new[] { %d, %d, %d, %d } },   // %s\n'
                    % (d, ms[0], ms[1], ms[2], ms[3],
                       " | ".join("%s=%s" % (TIERS[i], (exports[i].split("｜")[0] or "无") if i < len(exports) else "无")
                                  for i in range(4))))
        f.write("        };\n\n")
        f.write("        /// <summary>取该目录的 4 档时长（毫秒；0 = 无数据 ⇒ 调用方回落自己的默认口径）。</summary>\n")
        f.write("        public static bool TryGet(string dir, out int[] tiers)\n        {\n")
        f.write("            if (dir != null && Table.TryGetValue(dir, out tiers) && tiers.Length >= TierCount) return true;\n")
        f.write("            tiers = null;\n            return false;\n        }\n    }\n}\n")
    print("wrote %s  dirs=%d" % (OUT, len(rows)))
    if missing:
        print("未在分组表里找到的 export（%d 条，时长记 0 ⇒ 运行时回落默认口径）:" % len(missing))
        for x in missing:
            print("   ", x)
    for d, ms, _ in rows:
        if any(ms):
            print("%-26s idle=%-5d run=%-5d attack=%-5d die=%-5d" % (d, ms[0], ms[1], ms[2], ms[3]))
    return 0


if __name__ == "__main__":
    sys.exit(main())
