// <auto-generated> 由 tools/probes/gen-unit-anim-durations.py 生成 —— 请勿手改；
// 改数据请改 `策划/单位动画分组表.md`（生成物）后重跑该脚本。
// 数据 = 该目录每档 `Source` 记的那条 export 的 `timeline 帧数 ÷ FPS`（原版播放时长，毫秒）。
// 口径：`UnitAnimTable` 的 `Runs` 只存**唯一像素帧**（timeline 里的重复帧已折叠），
// 例 `axe_man_run1_5` = timeline 38 步 / 8 张像素帧 / 60 fps ⇒ 原版 0.633 s；
// 按 60 fps 直播那 8 张只有 0.133 s（快 4.75 倍）。⇒ 像素帧要在这段时间里播完（见 `UnitView.FpsFor`）。
using System.Collections.Generic;

namespace CR.View
{
    /// <summary>每目录每档的**原版时长**（毫秒；下标 = `UnitAnimTable.Idle/Walk/Attack/Die`）。</summary>
    public static class UnitAnimDurations
    {
        /// <summary>档位数（与 <see cref="UnitAnimTable"/> 同）。</summary>
        public const int TierCount = 4;

        private static readonly Dictionary<string, int[]> Table = new Dictionary<string, int[]>
        {
            { "building_inferno_tower_out", new[] { 33, 0, 0, 0 } },   // idle=inferno_blue_idle1_1 | run=无 | attack=无 | die=无
            { "building_mortar_out", new[] { 100, 0, 100, 0 } },   // idle=building_mortar1_idle1_5 | run=无 | attack=building_mortar1_attack1_5 | die=无
            { "building_xbow_out", new[] { 0, 0, 633, 0 } },   // idle=无 | run=无 | attack=building_xbow_attack1_1 | die=无
            { "chr_archer_out", new[] { 42, 667, 1000, 0 } },   // idle=archer1_idle1_5 | run=archer1_run1_5 | attack=archer1_attack1_5 | die=无
            { "chr_axe_man_out", new[] { 750, 633, 1017, 0 } },   // idle=axe_man_idle1_5 | run=axe_man_run1_5 | attack=axe_man_attack1_5 | die=无
            { "chr_baby_dragon_out", new[] { 600, 600, 733, 0 } },   // idle=baby_dragon_idle1_5 | run=baby_dragon_run1_5 | attack=baby_dragon_attack1_5 | die=无
            { "chr_balloon_out", new[] { 33, 2333, 1400, 0 } },   // idle=balloon1_idle1_1 | run=balloon1_run1_1 | attack=balloon1_attack1_1 | die=无
            { "chr_bandit_out", new[] { 967, 533, 767, 0 } },   // idle=bandit_idle1_5 | run=bandit_run1_5 | attack=bandit_attack1_5 | die=无
            { "chr_barbarian_out", new[] { 83, 667, 917, 0 } },   // idle=barbarian1_idle1_5 | run=barbarian1_run1_5 | attack=barbarian1_attack1_5 | die=无
            { "chr_bats_out", new[] { 333, 333, 467, 0 } },   // idle=bat_idle1_5 | run=bat_run1_5 | attack=bat_attack1_5 | die=无
            { "chr_battle_ram_out", new[] { 750, 750, 750, 0 } },   // idle=battle_ram_idle1_5 | run=battle_ram_run1_5 | attack=battle_ram_attack1_5 | die=无
            { "chr_black_knight_out", new[] { 33, 667, 900, 0 } },   // idle=BlackKnight_blue_idle1_5 | run=BlackKnight_blue_run1_5 | attack=BlackKnight_blue_attack1_5 | die=无
            { "chr_bomber_out", new[] { 1167, 667, 1100, 0 } },   // idle=chr_bomber_idle1_5 | run=chr_bomber_run1_5 | attack=chr_bomber_attack1_5 | die=无
            { "chr_bowler_out", new[] { 1000, 867, 1367, 0 } },   // idle=bowler_blue_idle1_5 | run=bowler_blue_run1_5 | attack=bowler_blue_attack1_5 | die=无
            { "chr_dark_witch_out", new[] { 833, 667, 1000, 0 } },   // idle=dark_witch_idle1_5 | run=dark_witch_run1_5 | attack=dark_witch_attack1_5 | die=无
            { "chr_electro_wizard_out", new[] { 617, 500, 1400, 0 } },   // idle=electro_wizard_idle1_5 | run=electro_wizard_run1_5 | attack=electro_wizard_attack1_5 | die=无
            { "chr_fire_firespirit_out", new[] { 933, 633, 933, 0 } },   // idle=firespirit_idle1_5 | run=firespirit_run1_5 | attack=firespirit_attack1_5 | die=无
            { "chr_flying_machine_out", new[] { 1667, 1667, 850, 0 } },   // idle=flying_machine_idle1_5 | run=flying_machine_run1_5 | attack=flying_machine_attack1_5 | die=无
            { "chr_giant_out", new[] { 1167, 1000, 933, 0 } },   // idle=giant1_idle1_5 | run=giant1_run1_5 | attack=giant1_attack1_5 | die=无
            { "chr_giant_skeleton_out", new[] { 33, 1000, 733, 0 } },   // idle=giant_skeleton_idle1_5 | run=giant_skeleton_run1_5 | attack=giant_skeleton_attack1_5 | die=无
            { "chr_goblin_out", new[] { 42, 750, 792, 0 } },   // idle=goblin1_idle1_5 | run=goblin1_run1_5 | attack=goblin1_attack1_5 | die=无
            { "chr_goblin_archer_out", new[] { 767, 733, 767, 0 } },   // idle=goblinArcher_blue_idle1_5 | run=goblinArcher_blue_run1_5 | attack=goblinArcher_blue_attack1_5 | die=无
            { "chr_goblin_blowdart_out", new[] { 1000, 800, 733, 0 } },   // idle=goblin_blowdart_idle1_5 | run=goblin_blowdart_run1_5 | attack=goblin_blowdart_attack1_5 | die=无
            { "chr_goblin_referee_out", new[] { 0, 400, 0, 0 } },   // idle=无 | run=goblin_referee_run1_3 | attack=无 | die=无
            { "chr_golem_out", new[] { 1000, 1800, 1333, 0 } },   // idle=golem1_idle1_5 | run=golem1_run1_5 | attack=golem1_attack1_5 | die=无
            { "chr_golemite_out", new[] { 1000, 1400, 1133, 0 } },   // idle=golemite_idle1_5 | run=golemite_run1_5 | attack=golemite_attack1_5 | die=无
            { "chr_hog_rider_out", new[] { 42, 708, 833, 0 } },   // idle=hog_rider_idle1_5 | run=hog_rider_run1_5 | attack=hog_rider_attack1_5 | die=无
            { "chr_ice_spirits_out", new[] { 833, 433, 467, 0 } },   // idle=icespirit_idle1_5 | run=icespirit_run1_5 | attack=icespirit_attack1_5 | die=无
            { "chr_ice_wizard_out", new[] { 1250, 667, 1458, 0 } },   // idle=ice_wizard_idle1_5 | run=ice_wizard_run1_5 | attack=ice_wizard_attack1_5 | die=无
            { "chr_knight_out", new[] { 33, 867, 1167, 0 } },   // idle=Knight_idle1_5 | run=Knight_run1_5 | attack=Knight_attack1_5 | die=无
            { "chr_lava_hound_out", new[] { 750, 750, 1625, 0 } },   // idle=lava_hound_idle1_5 | run=lava_hound_run1_5 | attack=lava_hound_attack1_5 | die=无
            { "chr_lava_pups_out", new[] { 750, 750, 2333, 0 } },   // idle=lava_pups_idle1_5 | run=lava_pups_run1_5 | attack=lava_pups_attack1_5 | die=无
            { "chr_mega_knight_out", new[] { 100, 1033, 1250, 0 } },   // idle=mega_knight_idle1_5 | run=mega_knight_run1_5 | attack=mega_knight_attack1_5 | die=无
            { "chr_mega_minion_out", new[] { 1333, 1333, 1083, 0 } },   // idle=mega_minion_idle1_5 | run=mega_minion_run1_5 | attack=mega_minion_attack1_5 | die=无
            { "chr_miner_out", new[] { 1000, 933, 800, 0 } },   // idle=miner_blue_idle1_5 | run=miner_blue_run1_5 | attack=miner_blue_attack1_5 | die=无
            { "chr_mini_pekka_out", new[] { 42, 667, 958, 0 } },   // idle=minipekka_idle1_5 | run=minipekka_run1_5 | attack=minipekka_attack1_5 | die=无
            { "chr_minion_out", new[] { 667, 667, 583, 0 } },   // idle=minion1_idle1_5 | run=minion1_run1_5 | attack=minion1_attack1_5 | die=无
            { "chr_movingcannon_out", new[] { 167, 1200, 883, 0 } },   // idle=moving_cannon_idle1_5 | run=moving_cannon_run1_5 | attack=moving_cannon_attack1_5 | die=无
            { "chr_musketeer_out", new[] { 33, 933, 1000, 0 } },   // idle=chr_musketeer_blue_idle1_5 | run=chr_musketeer_blue_run1_5 | attack=chr_musketeer_blue_attack1_5 | die=无
            { "chr_pekka_out", new[] { 83, 1250, 875, 0 } },   // idle=pekka_idle1_5 | run=pekka_run1_5 | attack=pekka_attack1_5 | die=无
            { "chr_prince_out", new[] { 33, 667, 900, 0 } },   // idle=Prince_idle1_5 | run=Prince_run1_5 | attack=Prince_attack1_5 | die=无
            { "chr_princess_out", new[] { 1250, 750, 1667, 0 } },   // idle=princess_idle1_5 | run=princess_run1_5 | attack=princess_attack1_5 | die=无
            { "chr_rage_barbarian_out", new[] { 1042, 667, 1375, 0 } },   // idle=rage_barbarian_idle1_5 | run=rage_barbarian_run1_5 | attack=rage_barbarian_attack1_5 | die=无
            { "chr_royal_giant_out", new[] { 3367, 1000, 1033, 0 } },   // idle=royalGiant_idle1_5 | run=royalGiant_run1_5 | attack=royalGiant_attack1_5 | die=无
            { "chr_skeleton_out", new[] { 83, 667, 583, 0 } },   // idle=skeleton1_idle1_5 | run=skeleton1_run1_5 | attack=skeleton1_attack1_5 | die=无
            { "chr_skeleton_balloon_out", new[] { 4933, 4933, 4933, 0 } },   // idle=skeleton_balloon_idle1_1 | run=skeleton_balloon_run1_1 | attack=skeleton_balloon_attack1_1 | die=无
            { "chr_skeleton_warrior_out", new[] { 33, 733, 567, 0 } },   // idle=skeletonWarrior_blue_idle1_5 | run=skeletonWarrior_blue_run1_5 | attack=skeletonWarrior_blue_attack1_5 | die=无
            { "chr_snowman_out", new[] { 1000, 1467, 1000, 0 } },   // idle=snowman_blue_idle1_5 | run=snowman_blue_run1_5 | attack=snowman_blue_attack1_5 | die=无
            { "chr_valkyrie_out", new[] { 42, 667, 1125, 0 } },   // idle=valkyrie1_idle1_5 | run=valkyrie1_run1_5 | attack=valkyrie1_attack1_5 | die=无
            { "chr_witch_out", new[] { 33, 800, 567, 0 } },   // idle=witch1_idle1_5 | run=witch1_run1_5 | attack=witch1_attack1_5 | die=无
            { "chr_wizard_out", new[] { 83, 667, 1250, 0 } },   // idle=wizard1_idle1_5 | run=wizard1_run1_5 | attack=wizard1_attack1_5 | die=无
            { "chr_zap_machine_out", new[] { 33, 1500, 500, 10033 } },   // idle=ZapMachine_idle1_5 | run=ZapMachine_run1_5 | attack=ZapMachine_attack1_5 | die=zapMachine_deathWheel
            { "effects_out", new[] { 0, 0, 0, 0 } },   // idle=master_builder_idle1 | run=无 | attack=dark_witch_attack | die=Death_blue/Death_purple/death_ground/death_particle
            { "ui_out", new[] { 0, 0, 0, 0 } },   // idle=无 | run=无 | attack=无 | die=darken_gradient/icon_tournament_suddendeath
        };

        /// <summary>取该目录的 4 档时长（毫秒；0 = 无数据 ⇒ 调用方回落自己的默认口径）。</summary>
        public static bool TryGet(string dir, out int[] tiers)
        {
            if (dir != null && Table.TryGetValue(dir, out tiers) && tiers.Length >= TierCount) return true;
            tiers = null;
            return false;
        }
    }
}
