// <auto-generated> 由 .ai-tmp/test/BC1-gen-table.py 生成 —— 请勿手改；改数据请改生成器的输入。
// 数据来源（三者交叉核对；均由 AT1 新口径重出）：
//   ① 策划/单位帧段表.md §3「可直接填 UnitView.AnimRanges 的四元组」
//      —— 重出命令：python tools/probes/sc-at1-resolve.py --root . --write-docs
//   ② .ai-tmp/test/AS1-anim-index.json（同一轮写出的数值产物：sids/ranges/fps/clip id；
//      文件名沿用 AS1 是因为 AT1 复用 AS1 生成链，内容已是 shape 记录序口径）
//   ③ .ai-tmp/test/AT1-档位可用性.tsv（每档 OK / 缺 / 悬空N帧/M帧）
//   + server/game/table/tsv/unit.tsv（hit_speed_ms，键 = sprite_dir 列）
// 口径⓪（AT1 根因）：`.sc` 的 `0x0C` id 数组是共享 id 空间里的「对象 id 列表」，
//   既可能是 shape 也可能是嵌套 movieclip；`frame_NNNN.png` 的 NNNN 是 **shape 记录序**，不是 id。
//   AT1 用 `sid -> 记录序` 查表 + 递归展开嵌套 clip 重解，可用性从 AS1 的 22/25/42 恢复到 45/10/34
//   （旧值 = 同口径回算，见 `.ai-tmp/test/BC1-resolve-out.txt` 第 1 行）。
// 口径①：配色侧。§3 打印的每一格取的是「两组配色里 sorted() 在前」的那一侧（= tools/probes/sc-as1-index.py:380）
//   对 chr_knight / chr_archer / chr_giant 等目录而言那是 `红(enemy_)` 组 ⇒ 玩家单位会渲染成红方配色。
//   本表按**主套(蓝)**取（原版玩家单位为蓝；§2 的「蓝/红」列同时并列两组，属同一权威文档）。
//   ⇒ 部分格与 §3 打印值不同（仅配色组，帧数可能差 1）；可用性/覆盖率与 §3 完全一致。
//   要严格照 §3 打印值：python .ai-tmp/test/BC1-gen-table.py --side=doc（一行切换）。
// 口径②：
//       不可用档位（缺 / 悬空）一律 Known=false ⇒ UnitView 回落「整目录循环」并 Warn 一次（已登记差异）。
using System.Collections.Generic;

namespace CR.View
{
    /// <summary>
    /// 单位/建筑动画帧段表（**纯数据**，与 UnitView 的实现分离 —— 便于 AS1/AT1 刷新结论后只改本文件）。
    /// <para>
    /// 每目录一条：4 个档位的 (start, count) + 帧号**段表** + 来源（export 名 / clip id 区间 / 配色侧）+ 可用性。
    /// `Runs` = 扁平化的 [起始帧号, 长度, 起始帧号, 长度, ...]（连续档位只有一对）；
    /// 用段表而不是单一区间，是因为 §3 明写「连续?=否时 start/count 不能当连续区间用」（如 chr_archer attack = 182-230 ∪ 247-251）。
    /// </para>
    /// <para>`Known == false` ⇒ 该档位**没有可用帧段**（素材无此动画 / `.sc` 引用越界 shapeID）⇒ 保持原行为（整目录）。</para>
    /// </summary>
    public static class UnitAnimTable
    {
        /// <summary>档位下标（与 <see cref="UnitView.AnimIdle"/> 等一致）。</summary>
        public const int Idle = 0, Walk = 1, Attack = 2, Die = 3;

        /// <summary>档位数（idle/walk/attack/die）。</summary>
        public const int TierCount = 4;

        /// <summary>一个档位的帧段。</summary>
        public struct Clip
        {
            /// <summary>是否有可用帧段（false ⇒ 回落整目录）。</summary>
            public bool Known;
            /// <summary>起始帧号（`frame_NNN` 的 NNN）；`Known==false` 时为 0。</summary>
            public int Start;
            /// <summary>帧数（= `Runs` 各段长度之和）；`Known==false` 时为 0。</summary>
            public int Count;
            /// <summary>帧号段表：[起始帧号, 长度, ...]。`Known==false` 时为 null。</summary>
            public int[] Runs;
            /// <summary>是否为一个连续区间（true ⇒ `Runs` 只有一对）。</summary>
            public bool Contiguous;
            /// <summary>来源（export 名 / clip id 区间 / 配色侧），供追溯与回归对照。</summary>
            public string Source;
        }

        /// <summary>一个目录的 4 档帧段 + 该目录的 .sc 帧率 + `hit_speed_ms`。</summary>
        public struct Entry
        {
            /// <summary>sprite 目录名（`ResPaths.UnitDir/BuildingDir` 里那一列，如 `chr_knight_out`）。</summary>
            public string Dir;
            /// <summary>4 档（下标 = Idle/Walk/Attack/Die）。</summary>
            public Clip[] Tiers;
            /// <summary>该目录 `.sc` 自带播放帧率（walk/die 用；attack 由 `hit_speed_ms` 反推，见 UnitView）。</summary>
            public int ScFps;
            /// <summary>`hit_speed_ms`（ms，来源 `server/game/table/tsv/unit.tsv`）；0 = 该目录无对应单位行。</summary>
            public int HitSpeedMs;
        }

        /// <summary>sprite 目录 → 帧段。</summary>
        public static readonly Dictionary<string, Entry> Table = new Dictionary<string, Entry>
        {
            // building_inferno_tower_out（表目录名 building_inferno_tower）
            ["building_inferno_tower_out"] = new Entry { Dir = "building_inferno_tower_out", ScFps = 30, HitSpeedMs = 400, Tiers = new[]
            {
                new Clip { Known = true, Start = 1, Count = 2, Contiguous = true, Runs = new[] { 1, 2 }, Source = "inferno_blue_idle1｜clip 5-5｜蓝(_blue_)" },
                new Clip { Known = false, Source = "" },   // walk 不可用
                new Clip { Known = false, Source = "" },   // attack 不可用
                new Clip { Known = false, Source = "" },   // die 不可用
            } },
            // building_mortar_out（表目录名 building_mortar）
            ["building_mortar_out"] = new Entry { Dir = "building_mortar_out", ScFps = 30, HitSpeedMs = 5000, Tiers = new[]
            {
                new Clip { Known = false, Source = "蓝(主套)｜building_mortar1_idle1" },   // idle 不可用
                new Clip { Known = false, Source = "" },   // walk 不可用
                new Clip { Known = true, Start = 0, Count = 5, Contiguous = true, Runs = new[] { 0, 5 }, Source = "building_mortar1_attack1｜clip 10-14｜蓝(主套)" },
                new Clip { Known = false, Source = "" },   // die 不可用
            } },
            // building_xbow_out（表目录名 building_xbow）
            ["building_xbow_out"] = new Entry { Dir = "building_xbow_out", ScFps = 30, HitSpeedMs = 300, Tiers = new[]
            {
                new Clip { Known = false, Source = "" },   // idle 不可用
                new Clip { Known = false, Source = "" },   // walk 不可用
                new Clip { Known = true, Start = 1, Count = 20, Contiguous = true, Runs = new[] { 1, 20 }, Source = "building_xbow_attack1｜clip 44-44｜蓝(主套)" },
                new Clip { Known = false, Source = "" },   // die 不可用
            } },
            // chr_archer_out（表目录名 chr_archer）
            ["chr_archer_out"] = new Entry { Dir = "chr_archer_out", ScFps = 24, HitSpeedMs = 900, Tiers = new[]
            {
                new Clip { Known = true, Start = 72, Count = 9, Contiguous = true, Runs = new[] { 72, 9 }, Source = "archer1_idle1｜clip 261-269｜蓝(主套)" },
                new Clip { Known = true, Start = 0, Count = 72, Contiguous = true, Runs = new[] { 0, 72 }, Source = "archer1_run1｜clip 252-260｜蓝(主套)" },
                new Clip { Known = true, Start = 72, Count = 54, Contiguous = true, Runs = new[] { 72, 54 }, Source = "archer1_attack1｜clip 270-278｜蓝(主套)" },
                new Clip { Known = false, Source = "" },   // die 不可用
            } },
            // chr_axe_man_out（表目录名 chr_axe_man）
            ["chr_axe_man_out"] = new Entry { Dir = "chr_axe_man_out", ScFps = 60, HitSpeedMs = 900, Tiers = new[]
            {
                new Clip { Known = true, Start = 144, Count = 18, Contiguous = true, Runs = new[] { 144, 18 }, Source = "axe_man_idle1/axe_man_red_idle1｜clip 515-575｜蓝(主套)" },
                new Clip { Known = true, Start = 0, Count = 144, Contiguous = true, Runs = new[] { 0, 144 }, Source = "axe_man_red_run1/axe_man_run1｜clip 376-791｜蓝(主套)" },
                new Clip { Known = true, Start = 144, Count = 216, Contiguous = true, Runs = new[] { 144, 216 }, Source = "axe_man_attack1/axe_man_attacking1/axe_man_red_attack1/axe_man_red_attacking1｜clip 542-790｜蓝(主套)" },
                new Clip { Known = false, Source = "" },   // die 不可用
            } },
            // chr_baby_dragon_out（表目录名 chr_baby_dragon）
            ["chr_baby_dragon_out"] = new Entry { Dir = "chr_baby_dragon_out", ScFps = 30, HitSpeedMs = 1500, Tiers = new[]
            {
                new Clip { Known = true, Start = 0, Count = 316, Contiguous = false, Runs = new[] { 0, 163, 173, 72, 326, 1, 328, 1, 330, 1, 332, 1, 334, 1, 336, 1, 338, 1, 340, 1, 342, 1, 344, 1, 346, 1, 348, 1, 350, 1, 352, 1, 354, 1, 356, 1, 358, 1, 360, 1, 362, 1, 364, 1, 366, 1, 368, 1, 370, 1, 372, 1, 374, 1, 376, 1, 378, 1, 380, 1, 382, 1, 384, 1, 386, 1, 388, 1, 390, 1, 392, 1, 394, 1, 396, 1, 398, 1, 400, 1, 402, 1, 404, 1, 406, 1, 408, 1, 410, 1, 412, 1, 414, 1, 416, 1, 418, 1, 420, 1, 422, 1, 424, 1, 426, 1, 428, 1, 430, 1, 432, 1, 434, 1, 436, 1, 438, 1, 440, 1, 442, 1, 444, 1, 446, 1, 448, 1, 450, 1, 452, 1, 454, 1, 456, 4, 461, 1, 463, 1, 465, 1, 467, 1, 469, 7, 477, 1 }, Source = "baby_dragon_idle1/inferno_dragon_idle1/inferno_dragon_red_idle1｜clip 717-978｜蓝(主套)" },
                new Clip { Known = true, Start = 0, Count = 316, Contiguous = false, Runs = new[] { 0, 163, 173, 72, 344, 1, 346, 1, 348, 1, 350, 1, 352, 1, 354, 1, 356, 1, 358, 1, 360, 1, 362, 1, 364, 1, 366, 1, 368, 1, 370, 1, 372, 1, 374, 1, 376, 1, 378, 1, 380, 1, 382, 1, 384, 1, 386, 1, 388, 1, 390, 1, 392, 1, 394, 1, 396, 1, 398, 1, 400, 1, 402, 1, 404, 1, 406, 1, 408, 1, 410, 1, 412, 1, 414, 1, 416, 1, 418, 1, 420, 1, 422, 1, 424, 1, 426, 1, 428, 1, 430, 1, 432, 1, 434, 1, 436, 1, 438, 1, 440, 1, 442, 1, 444, 1, 446, 1, 448, 1, 450, 1, 452, 1, 454, 1, 456, 4, 461, 1, 463, 1, 465, 1, 467, 1, 469, 7, 477, 1, 632, 9 }, Source = "baby_dragon_run1/inferno_dragon_red_run1/inferno_dragon_run1｜clip 708-961｜蓝(主套)" },
                new Clip { Known = true, Start = 0, Count = 417, Contiguous = false, Runs = new[] { 0, 327, 328, 1, 330, 1, 332, 1, 334, 1, 336, 1, 338, 1, 340, 1, 342, 1, 344, 1, 346, 1, 348, 1, 350, 1, 352, 1, 354, 1, 356, 1, 358, 1, 360, 1, 362, 1, 364, 1, 366, 1, 368, 1, 370, 1, 372, 1, 374, 1, 376, 1, 378, 1, 380, 1, 382, 1, 384, 1, 386, 1, 388, 1, 390, 1, 392, 1, 394, 1, 396, 1, 398, 1, 400, 1, 402, 1, 404, 1, 406, 1, 408, 1, 410, 1, 412, 1, 414, 1, 416, 1, 418, 1, 420, 1, 422, 1, 424, 1, 426, 1, 428, 1, 430, 1, 432, 1, 434, 1, 436, 1, 438, 1, 440, 1, 442, 1, 444, 1, 446, 1, 448, 1, 450, 1, 452, 1, 454, 1, 456, 4, 461, 1, 463, 1, 465, 1, 467, 1, 469, 7, 477, 1, 641, 10 }, Source = "baby_dragon_attack1/inferno_dragon_attack1/inferno_dragon_red_attack1｜clip 718-979｜蓝(主套)" },
                new Clip { Known = false, Source = "" },   // die 不可用
            } },
            // chr_balloon_out（表目录名 chr_balloon）
            ["chr_balloon_out"] = new Entry { Dir = "chr_balloon_out", ScFps = 30, HitSpeedMs = 2000, Tiers = new[]
            {
                new Clip { Known = true, Start = 0, Count = 3, Contiguous = false, Runs = new[] { 0, 2, 9, 1 }, Source = "balloon1_idle1｜clip 20-20｜蓝(主套)" },
                new Clip { Known = true, Start = 0, Count = 3, Contiguous = false, Runs = new[] { 0, 2, 9, 1 }, Source = "balloon1_run1｜clip 22-22｜蓝(主套)" },
                new Clip { Known = true, Start = 0, Count = 9, Contiguous = false, Runs = new[] { 0, 2, 3, 7 }, Source = "balloon1_attack1｜clip 19-19｜蓝(主套)" },
                new Clip { Known = false, Source = "" },   // die 不可用
            } },
            // chr_bandit_out（表目录名 chr_bandit）
            ["chr_bandit_out"] = new Entry { Dir = "chr_bandit_out", ScFps = 30, HitSpeedMs = 1000, Tiers = new[]
            {
                new Clip { Known = true, Start = 144, Count = 18, Contiguous = true, Runs = new[] { 144, 18 }, Source = "bandit_idle1/bandit_red_idle1｜clip 408-631｜蓝(主套)" },
                new Clip { Known = true, Start = 0, Count = 144, Contiguous = true, Runs = new[] { 0, 144 }, Source = "bandit_red_run1/bandit_run1｜clip 333-622｜蓝(主套)" },
                new Clip { Known = true, Start = 144, Count = 162, Contiguous = false, Runs = new[] { 144, 18, 181, 144 }, Source = "bandit_attack1/bandit_red_attack1｜clip 477-649｜蓝(主套)" },
                new Clip { Known = false, Source = "" },   // die 不可用
            } },
            // chr_barbarian_out（表目录名 chr_barbarian）
            ["chr_barbarian_out"] = new Entry { Dir = "chr_barbarian_out", ScFps = 24, HitSpeedMs = 1300, Tiers = new[]
            {
                new Clip { Known = true, Start = 144, Count = 45, Contiguous = false, Runs = new[] { 144, 9, 243, 9, 486, 9, 588, 9, 687, 9 }, Source = "angry_barbarian_idle1/angry_barbarian_red_idle1/angry_barbarian_td_idle1/angry_barbarian_td_red_idle1/barbarian1_idle1｜clip 705-1145｜蓝(主套)" },
                new Clip { Known = true, Start = 0, Count = 360, Contiguous = false, Runs = new[] { 0, 144, 342, 144, 867, 72 }, Source = "angry_barbarian_red_run1/angry_barbarian_run1/angry_barbarian_td_red_run1/angry_barbarian_td_run1/barbarian1_run1｜clip 687-1181｜蓝(主套)" },
                new Clip { Known = true, Start = 144, Count = 495, Contiguous = false, Runs = new[] { 144, 198, 486, 6, 495, 201, 939, 90 }, Source = "angry_barbarian_attack1/angry_barbarian_red_attack1/angry_barbarian_td_attack1/angry_barbarian_td_red_attack1/barbarian1_attack1｜clip 714-1190｜蓝(主套)" },
                new Clip { Known = false, Source = "" },   // die 不可用
            } },
            // chr_bats_out（表目录名 chr_bats）
            ["chr_bats_out"] = new Entry { Dir = "chr_bats_out", ScFps = 60, HitSpeedMs = 1300, Tiers = new[]
            {
                new Clip { Known = true, Start = 0, Count = 72, Contiguous = true, Runs = new[] { 0, 72 }, Source = "bat_idle1｜clip 99-131｜蓝(主套)" },
                new Clip { Known = true, Start = 0, Count = 72, Contiguous = true, Runs = new[] { 0, 72 }, Source = "bat_run1｜clip 90-98｜蓝(主套)" },
                new Clip { Known = true, Start = 0, Count = 90, Contiguous = true, Runs = new[] { 0, 90 }, Source = "bat_attack1｜clip 102-134｜蓝(主套)" },
                new Clip { Known = false, Source = "" },   // die 不可用
            } },
            // chr_battle_ram_out（表目录名 chr_battle_ram）
            ["chr_battle_ram_out"] = new Entry { Dir = "chr_battle_ram_out", ScFps = 24, HitSpeedMs = 400, Tiers = new[]
            {
                new Clip { Known = true, Start = 0, Count = 180, Contiguous = true, Runs = new[] { 0, 180 }, Source = "battle_ram_idle1/battle_ram_red_idle1｜clip 320-485｜蓝(主套)" },
                new Clip { Known = true, Start = 0, Count = 180, Contiguous = true, Runs = new[] { 0, 180 }, Source = "battle_ram_red_run1/battle_ram_run1｜clip 255-440｜蓝(主套)" },
                new Clip { Known = true, Start = 0, Count = 180, Contiguous = true, Runs = new[] { 0, 180 }, Source = "battle_ram_attack1/battle_ram_red_attack1｜clip 468-494｜蓝(主套)" },
                new Clip { Known = false, Source = "" },   // die 不可用
            } },
            // chr_black_knight_out（表目录名 chr_black_knight）
            ["chr_black_knight_out"] = new Entry { Dir = "chr_black_knight_out", ScFps = 30, HitSpeedMs = 0, Tiers = new[]
            {
                new Clip { Known = true, Start = 108, Count = 18, Contiguous = false, Runs = new[] { 108, 9, 368, 9 }, Source = "BlackKnight_blue_idle1/BlackKnight_shield_blue_idle1｜clip 1043-1087｜蓝(_blue_)" },
                new Clip { Known = true, Start = 18, Count = 180, Contiguous = false, Runs = new[] { 18, 90, 278, 90 }, Source = "BlackKnight_blue_run1/BlackKnight_shield_blue_run1｜clip 1034-1078｜蓝(_blue_)" },
                new Clip { Known = true, Start = 116, Count = 180, Contiguous = false, Runs = new[] { 116, 1, 189, 89, 368, 9, 449, 81 }, Source = "BlackKnight_blue_attack1/BlackKnight_shield_blue_attack1｜clip 1061-1105｜蓝(_blue_)" },
                new Clip { Known = false, Source = "" },   // die 不可用
            } },
            // chr_bomber_out（表目录名 chr_bomber）
            ["chr_bomber_out"] = new Entry { Dir = "chr_bomber_out", ScFps = 30, HitSpeedMs = 1800, Tiers = new[]
            {
                new Clip { Known = true, Start = 90, Count = 18, Contiguous = false, Runs = new[] { 90, 2, 105, 2, 120, 2, 135, 2, 150, 2, 165, 2, 180, 2, 195, 2, 210, 2 }, Source = "chr_bomber_RED_idle1/chr_bomber_idle1｜clip 443-493｜蓝(主套)" },
                new Clip { Known = true, Start = 0, Count = 180, Contiguous = false, Runs = new[] { 0, 90, 342, 90 }, Source = "chr_bomber_RED_run1/chr_bomber_run1｜clip 432-503｜蓝(主套)" },
                new Clip { Known = true, Start = 90, Count = 252, Contiguous = true, Runs = new[] { 90, 252 }, Source = "chr_bomber_RED_attack1/chr_bomber_attack1｜clip 444-494｜蓝(主套)" },
                new Clip { Known = false, Source = "" },   // die 不可用
            } },
            // chr_bowler_out（表目录名 chr_bowler）
            ["chr_bowler_out"] = new Entry { Dir = "chr_bowler_out", ScFps = 30, HitSpeedMs = 2500, Tiers = new[]
            {
                new Clip { Known = true, Start = 91, Count = 9, Contiguous = false, Runs = new[] { 91, 1, 93, 1, 95, 1, 97, 1, 99, 1, 101, 1, 103, 1, 300, 2 }, Source = "bowler_blue_idle1｜clip 529-539｜蓝(_blue_)" },
                new Clip { Known = true, Start = 196, Count = 117, Contiguous = false, Runs = new[] { 196, 104, 460, 13 }, Source = "bowler_blue_run1｜clip 521-556｜蓝(_blue_)" },
                new Clip { Known = true, Start = 302, Count = 117, Contiguous = false, Runs = new[] { 302, 91, 447, 13, 473, 13 }, Source = "bowler_blue_attack1｜clip 540-557｜蓝(_blue_)" },
                new Clip { Known = false, Source = "" },   // die 不可用
            } },
            // chr_dark_witch_out（表目录名 chr_dark_witch）
            ["chr_dark_witch_out"] = new Entry { Dir = "chr_dark_witch_out", ScFps = 60, HitSpeedMs = 0, Tiers = new[]
            {
                new Clip { Known = true, Start = 72, Count = 18, Contiguous = true, Runs = new[] { 72, 18 }, Source = "dark_witch_idle1/dark_witch_red_idle1｜clip 427-652｜蓝(主套)" },
                new Clip { Known = true, Start = 0, Count = 144, Contiguous = false, Runs = new[] { 0, 72, 272, 72 }, Source = "dark_witch_red_run1/dark_witch_run1｜clip 352-733｜蓝(主套)" },
                new Clip { Known = true, Start = 72, Count = 200, Contiguous = true, Runs = new[] { 72, 200 }, Source = "dark_witch_attack1/dark_witch_red_attack1｜clip 475-742｜蓝(主套)" },
                new Clip { Known = false, Source = "" },   // die 不可用
            } },
            // chr_electro_wizard_out（表目录名 chr_electro_wizard）
            ["chr_electro_wizard_out"] = new Entry { Dir = "chr_electro_wizard_out", ScFps = 60, HitSpeedMs = 1800, Tiers = new[]
            {
                new Clip { Known = true, Start = 136, Count = 18, Contiguous = true, Runs = new[] { 136, 18 }, Source = "electro_wizard_idle1/electro_wizard_red_idle1｜clip 488-656｜蓝(主套)" },
                new Clip { Known = true, Start = 0, Count = 144, Contiguous = false, Runs = new[] { 0, 136, 293, 8 }, Source = "electro_wizard_red_run1/electro_wizard_run1｜clip 345-687｜蓝(主套)" },
                new Clip { Known = false, Source = "蓝(主套)｜electro_wizard_attack1,electro_wizard_red_attack1" },   // attack 不可用
                new Clip { Known = false, Source = "" },   // die 不可用
            } },
            // chr_fire_firespirit_out（表目录名 chr_fire_firespirit）
            ["chr_fire_firespirit_out"] = new Entry { Dir = "chr_fire_firespirit_out", ScFps = 30, HitSpeedMs = 300, Tiers = new[]
            {
                new Clip { Known = true, Start = 0, Count = 10, Contiguous = true, Runs = new[] { 0, 10 }, Source = "firespirit_idle1｜clip 102-110｜蓝(主套)" },
                new Clip { Known = true, Start = 1, Count = 73, Contiguous = false, Runs = new[] { 1, 1, 10, 72 }, Source = "firespirit_run1｜clip 111-119｜蓝(主套)" },
                new Clip { Known = true, Start = 0, Count = 10, Contiguous = true, Runs = new[] { 0, 10 }, Source = "firespirit_attack1｜clip 85-101｜蓝(主套)" },
                new Clip { Known = false, Source = "" },   // die 不可用
            } },
            // chr_flying_machine_out（表目录名 chr_flying_machine）
            ["chr_flying_machine_out"] = new Entry { Dir = "chr_flying_machine_out", ScFps = 60, HitSpeedMs = 0, Tiers = new[]
            {
                new Clip { Known = true, Start = 0, Count = 90, Contiguous = true, Runs = new[] { 0, 90 }, Source = "flying_machine_idle1/flying_machine_red_idle1｜clip 184-228｜蓝(主套)" },
                new Clip { Known = true, Start = 0, Count = 90, Contiguous = true, Runs = new[] { 0, 90 }, Source = "flying_machine_red_run1/flying_machine_run1｜clip 167-229｜蓝(主套)" },
                new Clip { Known = true, Start = 0, Count = 90, Contiguous = true, Runs = new[] { 0, 90 }, Source = "flying_machine_attack1/flying_machine_red_attack1｜clip 97-230｜蓝(主套)" },
                new Clip { Known = false, Source = "" },   // die 不可用
            } },
            // chr_giant_out（表目录名 chr_giant）
            ["chr_giant_out"] = new Entry { Dir = "chr_giant_out", ScFps = 30, HitSpeedMs = 1500, Tiers = new[]
            {
                new Clip { Known = true, Start = 0, Count = 9, Contiguous = false, Runs = new[] { 0, 1, 20, 1, 40, 1, 60, 1, 80, 1, 100, 1, 120, 1, 140, 1, 448, 1 }, Source = "giant1_idle1｜clip 644-700｜蓝(主套)" },
                new Clip { Known = true, Start = 288, Count = 144, Contiguous = true, Runs = new[] { 288, 144 }, Source = "giant1_run1｜clip 668-676｜蓝(主套)" },
                new Clip { Known = true, Start = 0, Count = 90, Contiguous = false, Runs = new[] { 0, 1, 2, 1, 4, 1, 6, 1, 8, 1, 10, 1, 12, 1, 14, 1, 16, 1, 18, 1, 20, 1, 22, 1, 24, 1, 26, 1, 28, 1, 30, 1, 32, 1, 34, 1, 36, 1, 38, 1, 40, 1, 42, 1, 44, 1, 46, 1, 48, 1, 50, 1, 52, 1, 54, 1, 56, 1, 58, 1, 60, 1, 62, 1, 64, 1, 66, 1, 68, 1, 70, 1, 72, 1, 74, 1, 76, 1, 78, 1, 80, 1, 82, 1, 84, 1, 86, 1, 88, 1, 90, 1, 92, 1, 94, 1, 96, 1, 98, 1, 100, 1, 102, 1, 104, 1, 106, 1, 108, 1, 110, 1, 112, 1, 114, 1, 116, 1, 118, 1, 120, 1, 122, 1, 124, 1, 126, 1, 128, 1, 130, 1, 132, 1, 134, 1, 136, 1, 138, 1, 140, 1, 142, 1, 144, 1, 146, 1, 148, 1, 150, 1, 152, 1, 154, 1, 156, 1, 158, 1, 448, 1, 450, 1, 452, 1, 454, 1, 456, 1, 458, 1, 460, 1, 462, 1, 464, 1, 466, 1 }, Source = "giant1_attack1｜clip 645-701｜蓝(主套)" },
                new Clip { Known = false, Source = "" },   // die 不可用
            } },
            // chr_giant_skeleton_out（表目录名 chr_giant_skeleton）
            ["chr_giant_skeleton_out"] = new Entry { Dir = "chr_giant_skeleton_out", ScFps = 30, HitSpeedMs = 1400, Tiers = new[]
            {
                new Clip { Known = true, Start = 0, Count = 9, Contiguous = true, Runs = new[] { 0, 9 }, Source = "giant_skeleton_idle1｜clip 450-458｜蓝(主套)" },
                new Clip { Known = true, Start = 234, Count = 135, Contiguous = true, Runs = new[] { 234, 135 }, Source = "giant_skeleton_run1｜clip 486-494｜蓝(主套)" },
                new Clip { Known = true, Start = 0, Count = 90, Contiguous = false, Runs = new[] { 0, 9, 369, 81 }, Source = "giant_skeleton_attack1｜clip 495-503｜蓝(主套)" },
                new Clip { Known = false, Source = "" },   // die 不可用
            } },
            // chr_goblin_out（表目录名 chr_goblin）
            ["chr_goblin_out"] = new Entry { Dir = "chr_goblin_out", ScFps = 24, HitSpeedMs = 1100, Tiers = new[]
            {
                new Clip { Known = true, Start = 209, Count = 9, Contiguous = false, Runs = new[] { 209, 1, 217, 1, 225, 1, 233, 1, 241, 1, 249, 1, 257, 1, 265, 1, 273, 1 }, Source = "goblin1_idle1｜clip 332-340｜蓝(主套)" },
                new Clip { Known = true, Start = 0, Count = 72, Contiguous = true, Runs = new[] { 0, 72 }, Source = "goblin1_run1｜clip 288-296｜蓝(主套)" },
                new Clip { Known = true, Start = 209, Count = 72, Contiguous = true, Runs = new[] { 209, 72 }, Source = "goblin1_attack1｜clip 323-331｜蓝(主套)" },
                new Clip { Known = false, Source = "" },   // die 不可用
            } },
            // chr_goblin_archer_out（表目录名 chr_goblin_archer）
            ["chr_goblin_archer_out"] = new Entry { Dir = "chr_goblin_archer_out", ScFps = 30, HitSpeedMs = 1700, Tiers = new[]
            {
                new Clip { Known = true, Start = 80, Count = 18, Contiguous = true, Runs = new[] { 80, 18 }, Source = "goblinArcher_blue_idle1｜clip 353-380｜蓝(_blue_)" },
                new Clip { Known = true, Start = 0, Count = 90, Contiguous = false, Runs = new[] { 0, 80, 98, 10 }, Source = "goblinArcher_blue_run1｜clip 342-381｜蓝(_blue_)" },
                new Clip { Known = true, Start = 80, Count = 90, Contiguous = false, Runs = new[] { 80, 18, 198, 72 }, Source = "goblinArcher_blue_attack1｜clip 391-404｜蓝(_blue_)" },
                new Clip { Known = false, Source = "" },   // die 不可用
            } },
            // chr_goblin_blowdart_out（表目录名 chr_goblin_blowdart）
            ["chr_goblin_blowdart_out"] = new Entry { Dir = "chr_goblin_blowdart_out", ScFps = 30, HitSpeedMs = 700, Tiers = new[]
            {
                new Clip { Known = true, Start = 144, Count = 18, Contiguous = true, Runs = new[] { 144, 18 }, Source = "goblin_blowdart_idle1/goblin_blowdart_red_idle1｜clip 416-548｜蓝(主套)" },
                new Clip { Known = true, Start = 0, Count = 144, Contiguous = true, Runs = new[] { 0, 144 }, Source = "goblin_blowdart_red_run1/goblin_blowdart_run1｜clip 260-413｜蓝(主套)" },
                new Clip { Known = true, Start = 144, Count = 108, Contiguous = true, Runs = new[] { 144, 108 }, Source = "goblin_blowdart_attack1/goblin_blowdart_red_attack1｜clip 451-557｜蓝(主套)" },
                new Clip { Known = false, Source = "" },   // die 不可用
            } },
            // chr_goblin_referee_out（表目录名 chr_goblin_referee）
            ["chr_goblin_referee_out"] = new Entry { Dir = "chr_goblin_referee_out", ScFps = 60, HitSpeedMs = 0, Tiers = new[]
            {
                new Clip { Known = false, Source = "" },   // idle 不可用
                new Clip { Known = true, Start = 5, Count = 8, Contiguous = true, Runs = new[] { 5, 8 }, Source = "goblin_referee_run1｜clip 37-37｜蓝(主套)" },
                new Clip { Known = false, Source = "" },   // attack 不可用
                new Clip { Known = false, Source = "" },   // die 不可用
            } },
            // chr_golem_out（表目录名 chr_golem）
            ["chr_golem_out"] = new Entry { Dir = "chr_golem_out", ScFps = 30, HitSpeedMs = 0, Tiers = new[]
            {
                new Clip { Known = true, Start = 1, Count = 19, Contiguous = false, Runs = new[] { 1, 1, 217, 1, 227, 1, 237, 1, 247, 1, 257, 1, 267, 1, 277, 1, 287, 1, 297, 1, 307, 1, 313, 1, 319, 1, 325, 1, 331, 1, 337, 1, 343, 1, 349, 1, 355, 1 }, Source = "golem1_idle1/golem1_red_idle1｜clip 419-506｜蓝(主套)" },
                new Clip { Known = true, Start = 0, Count = 217, Contiguous = true, Runs = new[] { 0, 217 }, Source = "golem1_red_run1/golem1_run1｜clip 365-417｜蓝(主套)" },
                new Clip { Known = true, Start = 1, Count = 145, Contiguous = false, Runs = new[] { 1, 1, 217, 144 }, Source = "golem1_attack1/golem1_red_attack1｜clip 424-507｜蓝(主套)" },
                new Clip { Known = false, Source = "" },   // die 不可用
            } },
            // chr_golemite_out（表目录名 chr_golemite）
            ["chr_golemite_out"] = new Entry { Dir = "chr_golemite_out", ScFps = 30, HitSpeedMs = 0, Tiers = new[]
            {
                new Clip { Known = true, Start = 0, Count = 19, Contiguous = false, Runs = new[] { 0, 10, 307, 1, 313, 1, 319, 1, 325, 1, 331, 1, 337, 1, 343, 1, 349, 1, 355, 1 }, Source = "golemite_idle1/golemite_red_idle1｜clip 363-495｜蓝(主套)" },
                new Clip { Known = true, Start = 1, Count = 217, Contiguous = false, Runs = new[] { 1, 1, 91, 216 }, Source = "golemite_red_run1/golemite_run1｜clip 421-470｜蓝(主套)" },
                new Clip { Known = true, Start = 0, Count = 145, Contiguous = false, Runs = new[] { 0, 91, 307, 54 }, Source = "golemite_attack1/golemite_red_attack1｜clip 376-496｜蓝(主套)" },
                new Clip { Known = false, Source = "" },   // die 不可用
            } },
            // chr_hog_rider_out（表目录名 chr_hog_rider）
            ["chr_hog_rider_out"] = new Entry { Dir = "chr_hog_rider_out", ScFps = 24, HitSpeedMs = 1600, Tiers = new[]
            {
                new Clip { Known = true, Start = 72, Count = 18, Contiguous = false, Runs = new[] { 72, 9, 171, 9 }, Source = "hog_rider_idle1/hog_rider_red_idle1｜clip 351-377｜蓝(主套)" },
                new Clip { Known = true, Start = 0, Count = 144, Contiguous = false, Runs = new[] { 0, 72, 180, 72 }, Source = "hog_rider_red_run1/hog_rider_run1｜clip 342-386｜蓝(主套)" },
                new Clip { Known = true, Start = 72, Count = 198, Contiguous = false, Runs = new[] { 72, 108, 252, 90 }, Source = "hog_rider_attack1/hog_rider_red_attack1｜clip 360-395｜蓝(主套)" },
                new Clip { Known = false, Source = "" },   // die 不可用
            } },
            // chr_ice_spirits_out（表目录名 chr_ice_spirits）
            ["chr_ice_spirits_out"] = new Entry { Dir = "chr_ice_spirits_out", ScFps = 60, HitSpeedMs = 300, Tiers = new[]
            {
                new Clip { Known = true, Start = 0, Count = 10, Contiguous = true, Runs = new[] { 0, 10 }, Source = "icespirit_idle1｜clip 84-118｜蓝(主套)" },
                new Clip { Known = true, Start = 1, Count = 73, Contiguous = false, Runs = new[] { 1, 1, 10, 72 }, Source = "icespirit_run1｜clip 109-117｜蓝(主套)" },
                new Clip { Known = true, Start = 0, Count = 10, Contiguous = true, Runs = new[] { 0, 10 }, Source = "icespirit_attack1｜clip 99-108｜蓝(主套)" },
                new Clip { Known = false, Source = "" },   // die 不可用
            } },
            // chr_ice_wizard_out（表目录名 chr_ice_wizard）
            ["chr_ice_wizard_out"] = new Entry { Dir = "chr_ice_wizard_out", ScFps = 24, HitSpeedMs = 1700, Tiers = new[]
            {
                new Clip { Known = true, Start = 1, Count = 20, Contiguous = false, Runs = new[] { 1, 2, 122, 10, 142, 1, 153, 1, 164, 1, 175, 1, 186, 1, 197, 1, 208, 1, 219, 1 }, Source = "ice_wizard_idle1/ice_wizard_red_idle1｜clip 355-397｜蓝(主套)" },
                new Clip { Known = true, Start = 0, Count = 146, Contiguous = false, Runs = new[] { 0, 122, 230, 24 }, Source = "ice_wizard_red_run1/ice_wizard_run1｜clip 338-401｜蓝(主套)" },
                new Clip { Known = true, Start = 1, Count = 182, Contiguous = false, Runs = new[] { 1, 2, 131, 99, 254, 81 }, Source = "ice_wizard_attack1/ice_wizard_red_attack1｜clip 374-410｜蓝(主套)" },
                new Clip { Known = false, Source = "" },   // die 不可用
            } },
            // chr_knight_out（表目录名 chr_knight）
            ["chr_knight_out"] = new Entry { Dir = "chr_knight_out", ScFps = 30, HitSpeedMs = 1200, Tiers = new[]
            {
                new Clip { Known = true, Start = 108, Count = 8, Contiguous = true, Runs = new[] { 108, 8 }, Source = "Knight_idle1｜clip 495-503｜蓝(主套)" },
                new Clip { Known = true, Start = 0, Count = 108, Contiguous = true, Runs = new[] { 0, 108 }, Source = "Knight_run1｜clip 486-494｜蓝(主套)" },
                new Clip { Known = true, Start = 108, Count = 135, Contiguous = false, Runs = new[] { 108, 8, 359, 127 }, Source = "Knight_attack1｜clip 531-539｜蓝(主套)" },
                new Clip { Known = false, Source = "" },   // die 不可用
            } },
            // chr_lava_hound_out（表目录名 chr_lava_hound）
            ["chr_lava_hound_out"] = new Entry { Dir = "chr_lava_hound_out", ScFps = 24, HitSpeedMs = 1300, Tiers = new[]
            {
                new Clip { Known = true, Start = 2, Count = 162, Contiguous = false, Runs = new[] { 2, 9, 19, 9, 36, 9, 53, 9, 70, 9, 87, 9, 104, 9, 121, 9, 138, 9, 155, 9, 172, 9, 189, 9, 206, 9, 223, 9, 240, 9, 257, 9, 274, 9, 291, 9 }, Source = "lava_hound_idle1/lava_hound_red_idle1｜clip 333-359｜蓝(主套)" },
                new Clip { Known = true, Start = 2, Count = 162, Contiguous = false, Runs = new[] { 2, 9, 19, 9, 36, 9, 53, 9, 70, 9, 87, 9, 104, 9, 121, 9, 138, 9, 155, 9, 172, 9, 189, 9, 206, 9, 223, 9, 240, 9, 257, 9, 274, 9, 291, 9 }, Source = "lava_hound_red_run1/lava_hound_run1｜clip 324-341｜蓝(主套)" },
                new Clip { Known = true, Start = 0, Count = 306, Contiguous = true, Runs = new[] { 0, 306 }, Source = "lava_hound_attack1/lava_hound_red_attack1｜clip 306-323｜蓝(主套)" },
                new Clip { Known = false, Source = "" },   // die 不可用
            } },
            // chr_lava_pups_out（表目录名 chr_lava_pups）
            ["chr_lava_pups_out"] = new Entry { Dir = "chr_lava_pups_out", ScFps = 24, HitSpeedMs = 1300, Tiers = new[]
            {
                new Clip { Known = false, Source = "蓝(主套)｜lava_pups_idle1" },   // idle 不可用
                new Clip { Known = true, Start = 0, Count = 82, Contiguous = true, Runs = new[] { 0, 82 }, Source = "lava_pups_run1｜clip 165-173｜蓝(主套)" },
                new Clip { Known = true, Start = 0, Count = 163, Contiguous = true, Runs = new[] { 0, 163 }, Source = "lava_pups_attack1｜clip 183-191｜蓝(主套)" },
                new Clip { Known = false, Source = "" },   // die 不可用
            } },
            // chr_mega_knight_out（表目录名 chr_mega_knight）
            ["chr_mega_knight_out"] = new Entry { Dir = "chr_mega_knight_out", ScFps = 60, HitSpeedMs = 1700, Tiers = new[]
            {
                new Clip { Known = true, Start = 192, Count = 18, Contiguous = false, Runs = new[] { 192, 1, 212, 1, 233, 1, 255, 1, 277, 1, 299, 1, 321, 1, 343, 1, 365, 1, 486, 9 }, Source = "mega_knight_idle1/mega_knight_red_idle1｜clip 836-886｜蓝(主套)" },
                new Clip { Known = true, Start = 0, Count = 216, Contiguous = false, Runs = new[] { 0, 192, 584, 24 }, Source = "mega_knight_red_run1/mega_knight_run1｜clip 622-885｜蓝(主套)" },
                new Clip { Known = true, Start = 192, Count = 216, Contiguous = false, Runs = new[] { 192, 1, 212, 1, 233, 1, 255, 1, 277, 1, 299, 1, 321, 1, 343, 1, 365, 1, 387, 196, 608, 11 }, Source = "mega_knight_attack1/mega_knight_red_attack1｜clip 845-887｜蓝(主套)" },
                new Clip { Known = false, Source = "" },   // die 不可用
            } },
            // chr_mega_minion_out（表目录名 chr_mega_minion）
            ["chr_mega_minion_out"] = new Entry { Dir = "chr_mega_minion_out", ScFps = 24, HitSpeedMs = 1500, Tiers = new[]
            {
                new Clip { Known = true, Start = 0, Count = 144, Contiguous = true, Runs = new[] { 0, 144 }, Source = "mega_minion_idle1/mega_minion_red_idle1｜clip 252-269｜蓝(主套)" },
                new Clip { Known = false, Source = "蓝(主套)｜mega_minion_red_run1,mega_minion_run1" },   // walk 不可用
                new Clip { Known = true, Start = 0, Count = 252, Contiguous = true, Runs = new[] { 0, 252 }, Source = "mega_minion_attack1/mega_minion_red_attack1｜clip 277-368｜蓝(主套)" },
                new Clip { Known = false, Source = "" },   // die 不可用
            } },
            // chr_miner_out（表目录名 chr_miner）
            ["chr_miner_out"] = new Entry { Dir = "chr_miner_out", ScFps = 30, HitSpeedMs = 1200, Tiers = new[]
            {
                new Clip { Known = true, Start = 1, Count = 10, Contiguous = false, Runs = new[] { 1, 1, 298, 9 }, Source = "miner_blue_idle1｜clip 462-478｜蓝(_blue_)" },
                new Clip { Known = true, Start = 1, Count = 109, Contiguous = false, Runs = new[] { 1, 1, 307, 108 }, Source = "miner_blue_run1｜clip 479-487｜蓝(_blue_)" },
                new Clip { Known = true, Start = 1, Count = 91, Contiguous = false, Runs = new[] { 1, 1, 208, 90 }, Source = "miner_blue_attack1｜clip 452-460｜蓝(_blue_)" },
                new Clip { Known = false, Source = "" },   // die 不可用
            } },
            // chr_mini_pekka_out（表目录名 chr_mini_pekka）
            ["chr_mini_pekka_out"] = new Entry { Dir = "chr_mini_pekka_out", ScFps = 24, HitSpeedMs = 1600, Tiers = new[]
            {
                new Clip { Known = true, Start = 216, Count = 18, Contiguous = false, Runs = new[] { 216, 9, 316, 9 }, Source = "minipekka_idle1/minipekka_red_idle1｜clip 434-460｜蓝(主套)" },
                new Clip { Known = true, Start = 0, Count = 216, Contiguous = true, Runs = new[] { 0, 216 }, Source = "minipekka_red_run1/minipekka_run1｜clip 416-433｜蓝(主套)" },
                new Clip { Known = true, Start = 216, Count = 200, Contiguous = true, Runs = new[] { 216, 200 }, Source = "minipekka_attack1/minipekka_red_attack1｜clip 443-469｜蓝(主套)" },
                new Clip { Known = false, Source = "" },   // die 不可用
            } },
            // chr_minion_out（表目录名 chr_minion）
            ["chr_minion_out"] = new Entry { Dir = "chr_minion_out", ScFps = 24, HitSpeedMs = 1000, Tiers = new[]
            {
                new Clip { Known = true, Start = 0, Count = 72, Contiguous = true, Runs = new[] { 0, 72 }, Source = "minion1_idle1｜clip 288-296｜蓝(主套)" },
                new Clip { Known = true, Start = 0, Count = 72, Contiguous = true, Runs = new[] { 0, 72 }, Source = "minion1_run1｜clip 271-287｜蓝(主套)" },
                new Clip { Known = true, Start = 207, Count = 63, Contiguous = true, Runs = new[] { 207, 63 }, Source = "minion1_attack1｜clip 333-341｜蓝(主套)" },
                new Clip { Known = false, Source = "" },   // die 不可用
            } },
            // chr_movingcannon_out（表目录名 chr_movingcannon）
            ["chr_movingcannon_out"] = new Entry { Dir = "chr_movingcannon_out", ScFps = 60, HitSpeedMs = 1000, Tiers = new[]
            {
                new Clip { Known = true, Start = 4, Count = 73, Contiguous = false, Runs = new[] { 4, 2, 10, 2, 16, 2, 22, 2, 28, 2, 34, 2, 40, 2, 46, 2, 52, 2, 58, 2, 64, 2, 70, 5, 79, 8, 91, 4, 99, 34 }, Source = "broken_cannon_idle1/broken_cannon_red_idle1/moving_cannon_idle1/moving_cannon_red_idle1｜clip 227-377｜蓝(主套)" },
                new Clip { Known = true, Start = 0, Count = 127, Contiguous = false, Runs = new[] { 0, 102, 103, 1, 106, 3, 116, 3, 121, 1, 124, 3, 128, 1, 132, 13 }, Source = "broken_cannon_red_run1/broken_cannon_run1/moving_cannon_red_run1/moving_cannon_run1｜clip 148-435｜蓝(主套)" },
                new Clip { Known = true, Start = 4, Count = 73, Contiguous = false, Runs = new[] { 4, 2, 10, 2, 16, 2, 22, 2, 28, 2, 34, 2, 40, 2, 46, 2, 52, 2, 58, 2, 64, 2, 70, 5, 79, 8, 91, 4, 99, 34 }, Source = "broken_cannon_attack1/broken_cannon_red_attack1/moving_cannon_attack1/moving_cannon_red_attack1｜clip 256-434｜蓝(主套)" },
                new Clip { Known = false, Source = "" },   // die 不可用
            } },
            // chr_musketeer_out（表目录名 chr_musketeer）
            ["chr_musketeer_out"] = new Entry { Dir = "chr_musketeer_out", ScFps = 30, HitSpeedMs = 1000, Tiers = new[]
            {
                new Clip { Known = true, Start = 315, Count = 9, Contiguous = true, Runs = new[] { 315, 9 }, Source = "chr_musketeer_blue_idle1｜clip 450-458｜蓝(_blue_)" },
                new Clip { Known = true, Start = 207, Count = 108, Contiguous = true, Runs = new[] { 207, 108 }, Source = "chr_musketeer_blue_run1｜clip 441-449｜蓝(_blue_)" },
                new Clip { Known = true, Start = 315, Count = 99, Contiguous = true, Runs = new[] { 315, 99 }, Source = "chr_musketeer_blue_attack1｜clip 459-467｜蓝(_blue_)" },
                new Clip { Known = false, Source = "" },   // die 不可用
            } },
            // chr_pekka_out（表目录名 chr_pekka）
            ["chr_pekka_out"] = new Entry { Dir = "chr_pekka_out", ScFps = 24, HitSpeedMs = 1800, Tiers = new[]
            {
                new Clip { Known = true, Start = 126, Count = 9, Contiguous = true, Runs = new[] { 126, 9 }, Source = "pekka_idle1｜clip 405-413｜蓝(主套)" },
                new Clip { Known = true, Start = 0, Count = 126, Contiguous = true, Runs = new[] { 0, 126 }, Source = "pekka_run1｜clip 396-404｜蓝(主套)" },
                new Clip { Known = true, Start = 126, Count = 72, Contiguous = false, Runs = new[] { 126, 9, 333, 63 }, Source = "pekka_attack1｜clip 441-449｜蓝(主套)" },
                new Clip { Known = false, Source = "" },   // die 不可用
            } },
            // chr_prince_out（表目录名 chr_prince）
            ["chr_prince_out"] = new Entry { Dir = "chr_prince_out", ScFps = 30, HitSpeedMs = 1400, Tiers = new[]
            {
                new Clip { Known = true, Start = 90, Count = 18, Contiguous = false, Runs = new[] { 90, 9, 261, 9 }, Source = "Prince_idle1/Prince_red_idle1｜clip 531-566｜蓝(主套)" },
                new Clip { Known = true, Start = 0, Count = 180, Contiguous = false, Runs = new[] { 0, 90, 432, 90 }, Source = "Prince_red_run1/Prince_run1｜clip 522-593｜蓝(主套)" },
                new Clip { Known = true, Start = 90, Count = 198, Contiguous = false, Runs = new[] { 90, 9, 171, 189 }, Source = "Prince_attack1/Prince_red_attack1｜clip 549-575｜蓝(主套)" },
                new Clip { Known = false, Source = "" },   // die 不可用
            } },
            // chr_princess_out（表目录名 chr_princess）
            ["chr_princess_out"] = new Entry { Dir = "chr_princess_out", ScFps = 24, HitSpeedMs = 3000, Tiers = new[]
            {
                new Clip { Known = true, Start = 0, Count = 36, Contiguous = false, Runs = new[] { 0, 9, 253, 9, 431, 9, 496, 9 }, Source = "princess_idle1/princess_red_idle1/princess_tower_idle1/princess_tower_red_idle1｜clip 749-985｜蓝(主套)" },
                new Clip { Known = true, Start = 117, Count = 280, Contiguous = false, Runs = new[] { 117, 136, 440, 56, 574, 88 }, Source = "princess_red_run1/princess_run1/princess_tower_red_run1/princess_tower_run1｜clip 811-1008｜蓝(主套)" },
                new Clip { Known = true, Start = 0, Count = 450, Contiguous = false, Runs = new[] { 0, 117, 262, 169, 496, 78, 662, 86 }, Source = "princess_attack1/princess_red_attack1/princess_tower_attack1/princess_tower_red_attack1｜clip 770-1022｜蓝(主套)" },
                new Clip { Known = false, Source = "" },   // die 不可用
            } },
            // chr_rage_barbarian_out（表目录名 chr_rage_barbarian）
            ["chr_rage_barbarian_out"] = new Entry { Dir = "chr_rage_barbarian_out", ScFps = 24, HitSpeedMs = 0, Tiers = new[]
            {
                new Clip { Known = true, Start = 112, Count = 18, Contiguous = false, Runs = new[] { 112, 16, 170, 1, 211, 1 }, Source = "rage_barbarian_idle1/rage_barbarian_red_idle1｜clip 362-407｜蓝(主套)" },
                new Clip { Known = true, Start = 0, Count = 144, Contiguous = false, Runs = new[] { 0, 112, 212, 32 }, Source = "rage_barbarian_red_run1/rage_barbarian_run1｜clip 346-411｜蓝(主套)" },
                new Clip { Known = true, Start = 130, Count = 180, Contiguous = false, Runs = new[] { 130, 40, 171, 40, 246, 100 }, Source = "rage_barbarian_attack1/rage_barbarian_red_attack1｜clip 388-425｜蓝(主套)" },
                new Clip { Known = false, Source = "" },   // die 不可用
            } },
            // chr_royal_giant_out（表目录名 chr_royal_giant）
            ["chr_royal_giant_out"] = new Entry { Dir = "chr_royal_giant_out", ScFps = 30, HitSpeedMs = 1700, Tiers = new[]
            {
                new Clip { Known = true, Start = 144, Count = 18, Contiguous = false, Runs = new[] { 144, 10, 164, 1, 175, 1, 186, 1, 197, 1, 208, 1, 219, 1, 230, 1, 241, 1 }, Source = "royalGiant_idle1/royalGiant_red_idle1｜clip 487-529｜蓝(主套)" },
                new Clip { Known = true, Start = 0, Count = 288, Contiguous = false, Runs = new[] { 0, 144, 252, 144 }, Source = "royalGiant_red_run1/royalGiant_run1｜clip 477-539｜蓝(主套)" },
                new Clip { Known = true, Start = 153, Count = 180, Contiguous = false, Runs = new[] { 153, 99, 396, 81 }, Source = "royalGiant_attack1/royalGiant_red_attack1｜clip 506-548｜蓝(主套)" },
                new Clip { Known = false, Source = "" },   // die 不可用
            } },
            // chr_skeleton_out（表目录名 chr_skeleton）
            ["chr_skeleton_out"] = new Entry { Dir = "chr_skeleton_out", ScFps = 24, HitSpeedMs = 1000, Tiers = new[]
            {
                new Clip { Known = true, Start = 72, Count = 9, Contiguous = true, Runs = new[] { 72, 9 }, Source = "skeleton1_idle1｜clip 128-136｜蓝(主套)" },
                new Clip { Known = true, Start = 0, Count = 72, Contiguous = true, Runs = new[] { 0, 72 }, Source = "skeleton1_run1｜clip 119-127｜蓝(主套)" },
                new Clip { Known = true, Start = 72, Count = 45, Contiguous = true, Runs = new[] { 72, 45 }, Source = "skeleton1_attack1｜clip 137-145｜蓝(主套)" },
                new Clip { Known = false, Source = "" },   // die 不可用
            } },
            // chr_skeleton_balloon_out（表目录名 chr_skeleton_balloon）
            ["chr_skeleton_balloon_out"] = new Entry { Dir = "chr_skeleton_balloon_out", ScFps = 60, HitSpeedMs = 0, Tiers = new[]
            {
                new Clip { Known = true, Start = 0, Count = 6, Contiguous = true, Runs = new[] { 0, 6 }, Source = "skeleton_balloon_idle1/skeleton_balloon_red_idle1｜clip 15-21｜蓝(主套)" },
                new Clip { Known = true, Start = 0, Count = 6, Contiguous = true, Runs = new[] { 0, 6 }, Source = "skeleton_balloon_red_run1/skeleton_balloon_run1｜clip 14-24｜蓝(主套)" },
                new Clip { Known = true, Start = 0, Count = 6, Contiguous = true, Runs = new[] { 0, 6 }, Source = "skeleton_balloon_attack1/skeleton_balloon_red_attack1｜clip 16-23｜蓝(主套)" },
                new Clip { Known = false, Source = "" },   // die 不可用
            } },
            // chr_skeleton_warrior_out（表目录名 chr_skeleton_warrior）
            ["chr_skeleton_warrior_out"] = new Entry { Dir = "chr_skeleton_warrior_out", ScFps = 30, HitSpeedMs = 0, Tiers = new[]
            {
                new Clip { Known = true, Start = 18, Count = 18, Contiguous = false, Runs = new[] { 18, 11, 650, 1, 660, 1, 670, 1, 680, 1, 690, 1, 700, 1, 710, 1 }, Source = "skeletonWarrior_blue_idle1/skeletonWarrior_blue_shield_idle1｜clip 738-827｜蓝(_blue_)" },
                new Clip { Known = true, Start = 29, Count = 180, Contiguous = false, Runs = new[] { 29, 90, 128, 90 }, Source = "skeletonWarrior_blue_run1/skeletonWarrior_blue_shield_run1｜clip 749-767｜蓝(_blue_)" },
                new Clip { Known = true, Start = 18, Count = 180, Contiguous = false, Runs = new[] { 18, 11, 119, 9, 218, 81, 641, 79 }, Source = "skeletonWarrior_blue_attack1/skeletonWarrior_blue_shield_attack1｜clip 758-820｜蓝(_blue_)" },
                new Clip { Known = false, Source = "" },   // die 不可用
            } },
            // chr_snowman_out（表目录名 chr_snowman）
            ["chr_snowman_out"] = new Entry { Dir = "chr_snowman_out", ScFps = 30, HitSpeedMs = 0, Tiers = new[]
            {
                new Clip { Known = true, Start = 192, Count = 9, Contiguous = false, Runs = new[] { 192, 1, 199, 1, 206, 1, 237, 1, 244, 1, 251, 1, 258, 1, 265, 1, 272, 1 }, Source = "snowman_blue_idle1｜clip 543-640｜蓝(_blue_)" },
                new Clip { Known = true, Start = 0, Count = 144, Contiguous = false, Runs = new[] { 0, 2, 3, 2, 6, 2, 9, 2, 12, 2, 15, 2, 18, 2, 21, 2, 24, 2, 27, 2, 30, 2, 33, 2, 36, 2, 39, 2, 42, 2, 45, 2, 48, 2, 51, 2, 54, 2, 57, 2, 60, 2, 63, 2, 66, 2, 69, 2, 72, 2, 75, 2, 78, 2, 81, 2, 84, 2, 87, 2, 90, 2, 93, 2, 96, 2, 99, 2, 102, 2, 105, 2, 108, 2, 111, 2, 114, 2, 117, 2, 120, 2, 123, 2, 126, 2, 129, 2, 132, 2, 135, 2, 138, 2, 141, 2, 144, 1, 146, 2, 149, 2, 152, 2, 155, 2, 158, 2, 161, 2, 164, 2, 167, 2, 170, 2, 173, 2, 176, 2, 179, 2, 182, 2, 185, 2, 188, 2, 191, 1, 213, 1, 215, 2, 218, 2, 221, 2, 224, 2, 227, 2, 230, 2, 233, 2, 236, 1 }, Source = "snowman_blue_run1｜clip 534-593｜蓝(_blue_)" },
                new Clip { Known = true, Start = 192, Count = 63, Contiguous = false, Runs = new[] { 192, 21, 237, 42 }, Source = "snowman_blue_attack1｜clip 550-647｜蓝(_blue_)" },
                new Clip { Known = false, Source = "" },   // die 不可用
            } },
            // chr_valkyrie_out（表目录名 chr_valkyrie）
            ["chr_valkyrie_out"] = new Entry { Dir = "chr_valkyrie_out", ScFps = 24, HitSpeedMs = 1500, Tiers = new[]
            {
                new Clip { Known = true, Start = 72, Count = 9, Contiguous = true, Runs = new[] { 72, 9 }, Source = "valkyrie1_idle1｜clip 388-396｜蓝(主套)" },
                new Clip { Known = true, Start = 0, Count = 72, Contiguous = true, Runs = new[] { 0, 72 }, Source = "valkyrie1_run1｜clip 379-387｜蓝(主套)" },
                new Clip { Known = true, Start = 163, Count = 109, Contiguous = false, Runs = new[] { 163, 1, 271, 108 }, Source = "valkyrie1_attack1｜clip 425-433｜蓝(主套)" },
                new Clip { Known = false, Source = "" },   // die 不可用
            } },
            // chr_witch_out（表目录名 chr_witch）
            ["chr_witch_out"] = new Entry { Dir = "chr_witch_out", ScFps = 30, HitSpeedMs = 1100, Tiers = new[]
            {
                new Clip { Known = true, Start = 72, Count = 9, Contiguous = true, Runs = new[] { 72, 9 }, Source = "witch1_idle1｜clip 262-270｜蓝(主套)" },
                new Clip { Known = true, Start = 0, Count = 72, Contiguous = true, Runs = new[] { 0, 72 }, Source = "witch1_run1｜clip 253-261｜蓝(主套)" },
                new Clip { Known = true, Start = 72, Count = 55, Contiguous = false, Runs = new[] { 72, 9, 162, 1, 208, 45 }, Source = "witch1_attack1｜clip 299-307｜蓝(主套)" },
                new Clip { Known = false, Source = "" },   // die 不可用
            } },
            // chr_wizard_out（表目录名 chr_wizard）
            ["chr_wizard_out"] = new Entry { Dir = "chr_wizard_out", ScFps = 24, HitSpeedMs = 1400, Tiers = new[]
            {
                new Clip { Known = true, Start = 144, Count = 18, Contiguous = false, Runs = new[] { 144, 9, 240, 9 }, Source = "wizard1_idle1/wizard1_red_idle1｜clip 331-384｜蓝(主套)" },
                new Clip { Known = true, Start = 0, Count = 144, Contiguous = true, Runs = new[] { 0, 144 }, Source = "wizard1_red_run1/wizard1_run1｜clip 313-330｜蓝(主套)" },
                new Clip { Known = true, Start = 144, Count = 168, Contiguous = true, Runs = new[] { 144, 168 }, Source = "wizard1_attack1/wizard1_red_attack1｜clip 351-393｜蓝(主套)" },
                new Clip { Known = false, Source = "" },   // die 不可用
            } },
            // chr_zap_machine_out（表目录名 chr_zap_machine）
            ["chr_zap_machine_out"] = new Entry { Dir = "chr_zap_machine_out", ScFps = 30, HitSpeedMs = 0, Tiers = new[]
            {
                new Clip { Known = true, Start = 0, Count = 137, Contiguous = false, Runs = new[] { 0, 1, 4, 2, 10, 15, 28, 2, 34, 4, 41, 2, 47, 4, 54, 2, 60, 4, 67, 2, 73, 4, 80, 2, 86, 4, 92, 2, 98, 4, 105, 2, 111, 4, 118, 2, 124, 4, 131, 2, 137, 4, 144, 2, 150, 4, 157, 2, 163, 4, 170, 2, 176, 4, 183, 2, 189, 4, 196, 2, 202, 4, 209, 2, 215, 6, 222, 8, 236, 19 }, Source = "ZapMachine_Blue_idle1｜clip 534-606｜蓝(_blue_)" },
                new Clip { Known = true, Start = 0, Count = 244, Contiguous = false, Runs = new[] { 0, 9, 10, 23, 34, 12, 47, 12, 60, 12, 73, 12, 86, 11, 98, 12, 111, 12, 124, 12, 137, 12, 150, 12, 163, 12, 176, 12, 189, 12, 202, 12, 215, 6, 222, 33, 259, 6 }, Source = "ZapMachine_Blue_run1｜clip 499-609｜蓝(_blue_)" },
                new Clip { Known = true, Start = 0, Count = 134, Contiguous = false, Runs = new[] { 0, 1, 4, 2, 10, 15, 28, 2, 34, 4, 41, 2, 47, 4, 54, 2, 60, 4, 67, 2, 73, 3, 80, 2, 86, 4, 92, 2, 98, 3, 105, 2, 111, 3, 118, 2, 124, 4, 131, 2, 137, 4, 144, 2, 150, 4, 157, 2, 163, 4, 170, 2, 176, 4, 183, 2, 189, 4, 196, 2, 202, 4, 209, 2, 215, 6, 222, 8, 236, 19 }, Source = "ZapMachine_Blue_attack1｜clip 552-579｜蓝(_blue_)" },
                new Clip { Known = false, Source = "" },   // die 不可用
            } },
            // effects_out（表目录名 effects）
            ["effects_out"] = new Entry { Dir = "effects_out", ScFps = 60, HitSpeedMs = 0, Tiers = new[]
            {
                new Clip { Known = true, Start = 299, Count = 2, Contiguous = true, Runs = new[] { 299, 2 }, Source = "master_builder_idle1｜clip 831-831｜蓝(主套)" },
                new Clip { Known = false, Source = "" },   // walk 不可用
                new Clip { Known = true, Start = 49, Count = 2, Contiguous = true, Runs = new[] { 49, 2 }, Source = "dark_witch_attack｜clip 151-151｜蓝(主套)" },
                new Clip { Known = true, Start = 50, Count = 9, Contiguous = false, Runs = new[] { 50, 1, 52, 1, 62, 2, 65, 5 }, Source = "Death_blue/Death_purple/death_ground/death_particle｜clip 196-215｜蓝(主套)" },
            } },
            // ui_out（表目录名 ui）
            ["ui_out"] = new Entry { Dir = "ui_out", ScFps = 60, HitSpeedMs = 0, Tiers = new[]
            {
                new Clip { Known = false, Source = "" },   // idle 不可用
                new Clip { Known = false, Source = "" },   // walk 不可用
                new Clip { Known = false, Source = "" },   // attack 不可用
                new Clip { Known = true, Start = 153, Count = 4, Contiguous = false, Runs = new[] { 153, 1, 274, 1, 376, 1, 465, 1 }, Source = "darken_gradient/icon_tournament_suddendeath｜clip 1204-4026｜蓝(主套)" },
            } },
        };

        /// <summary>取某 sprite 目录的帧段；不在表中返回 false（⇒ UnitView 报到"未收录"并整目录循环）。</summary>
        public static bool TryGet(string dir, out Entry entry)
        {
            return Table.TryGetValue(dir ?? string.Empty, out entry);
        }

        /// <summary>表里已知档位的目录数（自检用）。</summary>
        public static int DirCount => Table.Count;
    }
}
